/* Authored movement options. General strength/coordination support is not proof of punch transfer. */
(() => {
  'use strict';
  const D=window.BOXING_DATA,E=window.ROUNDWORK_EVIDENCE,V={...window.ROUNDWORK_VIDEOS},ES=window.ROUNDWORK_ES;
  window.ROUNDWORK_VIDEOS=V;
  const pairs=[],L=(en,es)=>{pairs.push([en,es]);ES[en]=es;return en;};
  const by=id=>D.exercises.find(e=>e.id===id),copy=id=>JSON.parse(JSON.stringify(by(id)));
  const warmURL='https://www.nsca.com/education/articles/kinetic-select/introduction-to-dynamic-warm-up/';
  const ropeURL='https://contentcdn.eacefitness.com/assets/education-resources/lifestyle/fitfacts/pdfs/fitfacts/itemid_2688.pdf';
  const lungeURL='https://www.puregym.com/exercises/legs/quad-exercises/lunges/walking-lunges/';
  const barURL='https://www.puregym.com/blog/female-lower-body-leg-workout/';
  const coreURL='https://www.nsca.com/contentassets/1066cf7e2c9d4e61b3c1a6e3fea988e0/coach-7.1.2-implementing-core-training-concepts-into-strength-training-for-sport.pdf';
  const source=(url,label)=>({url,label,linkLabel:L('Expert reference / demo','Referencia experta / demostración')});
  const substitute=L('Replaces this training slot, not an extra exercise. Mechanics and boxing transfer differ; follow the displayed dose.','Sustituye este bloque, sin añadir otro ejercicio. La mecánica y la transferencia al boxeo difieren; sigue la dosis mostrada.');
  const add=(base,extra)=>{const ex={...copy(base),alternatives:[],substitutionNote:substitute,...extra};D.exercises.push(ex);return ex;};
  const pairList=(en,es)=>en.map((s,i)=>L(s,es[i]));
  D.equipment.push({id:'jumpRope',name:L('Light skipping rope','Cuerda ligera para saltar')},{id:'barbell',name:L('Barbell, plates and collars','Barra, discos y cierres')},{id:'rack',name:L('Suitable rack and coach-checked bar setup','Soporte adecuado y ajuste de barra revisado por entrenador')});
  add('warmup',{id:'warmRope',demo:'jumpRope',name:L('Easy jump-rope warm-up','Calentamiento suave con cuerda'),equipment:['jumpRope','floor'],source:source(ropeURL,L('ACE jump-rope technique','Técnica de salto con cuerda de ACE')),
    purpose:L('Raise temperature with low, easy skips, then mobilise and rehearse today’s movements.','Eleva la temperatura con saltos bajos y suaves, después moviliza y ensaya los movimientos de hoy.'),
    setup:L('Use a light rope on a clear non-slip floor. Handles reach about chest height when one foot holds the rope’s centre.','Usa una cuerda ligera sobre suelo despejado y antideslizante. Los mangos llegan aproximadamente al pecho al pisar el centro de la cuerda.'),
    steps:pairList(['Spend 3 minutes alternating easy low skips with marching breaks. If new, use about 20 seconds skipping and 10 seconds marching.','Spend 2 minutes moving ankles, hips and shoulders through comfortable ranges.','Spend 3 minutes rehearsing today’s movements; use light ramp-up sets before working weights.'],['Dedica 3 minutos a alternar saltos bajos suaves y pausas de marcha. Si empiezas, usa unos 20 segundos de salto y 10 de marcha.','Dedica 2 minutos a mover tobillos, caderas y hombros en rangos cómodos.','Dedica 3 minutos a ensayar los movimientos de hoy; haz series de aproximación ligeras antes de las cargas de trabajo.']),
    cues:pairList(['Relax shoulders; turn the rope with your wrists and land quietly.','Keep an easy conversational pace. March instead if calves or ankles feel uncomfortable.'],['Relaja los hombros; gira la cuerda con las muñecas y aterriza sin ruido.','Mantén un ritmo suave que permita conversar. Marcha si sientes molestias en pantorrillas o tobillos.']),
    avoid:pairList(['No double-unders, weighted ropes or maximal skipping intervals in this warm-up.'],['Sin saltos dobles, cuerdas lastradas ni intervalos máximos en este calentamiento.'])});
  for(const [id,name,esName,gear,demo,first,esFirst,video] of [
    ['warmBike','Bike + movement warm-up','Bicicleta y movilidad para calentar',['bike','floor'],'bike','Cycle gently for 3 minutes; increase pace gradually without breathlessness.','Pedalea suavemente durante 3 minutos; aumenta el ritmo gradualmente sin perder el aliento.','bike'],
    ['warmShadow','Stance + movement warm-up','Postura y movilidad para calentar',['floor'],'shadow','Walk and practise relaxed coach-taught stance steps for 3 minutes; no fast punching.','Camina y practica pasos relajados de postura enseñados por tu entrenador durante 3 minutos; sin golpes rápidos.','shadow']
  ]){add('warmup',{id,name:L(name,esName),equipment:gear,demo,steps:[L(first,esFirst),by('warmRope').steps[1],by('warmRope').steps[2]],source:source(warmURL,L('NSCA dynamic warm-up guidance','Orientación de calentamiento dinámico de NSCA'))});V[id]={...V[video],note:L('This shows one component only. Complete the mobility and rehearsal steps in the guide; keep the warm-up easy.','Muestra solo una parte. Completa la movilidad y el ensayo de la guía; mantén el calentamiento suave.')};}
  const walkingSteps=pairList(['Step forward on two hip-width tracks; bend both knees to a comfortable depth.','Push through the front foot and bring the rear leg forward into the next step.','Alternate legs under control. Pause to balance; turn only after a set, with weights secure.'],['Avanza por dos líneas al ancho de caderas; flexiona ambas rodillas hasta una profundidad cómoda.','Empuja con el pie delantero y lleva la pierna trasera hacia el siguiente paso.','Alterna las piernas con control. Pausa para equilibrarte; gira solo al terminar una serie, con las cargas seguras.']);
  for(const [id,name,esName,gear,setup,esSetup,min] of [
    ['walkingBody','Bodyweight walking lunge','Zancada caminando con peso corporal',['floor','walkSpace'],'Stand tall with hands free and a clear level walking lane. Learn this before adding load.','Ponte erguido con manos libres y un carril despejado y nivelado. Aprende esto antes de añadir carga.','rookie'],
    ['walkingDumbbell','Dumbbell walking lunge','Zancada caminando con mancuernas',['dumbbells','floor','walkSpace'],'Use familiar light dumbbells at your sides. Confirm a clear lane; rehearse without weights first.','Usa mancuernas ligeras conocidas a los lados. Confirma un carril despejado; ensaya primero sin peso.','intermediate'],
    ['walkingBarbell','Barbell walking lunge','Zancada caminando con barra',['barbell','rack','floor','walkSpace'],'Advanced, familiar lifters only: ask a coach to check rack height, collars, bar position on the upper back and clear walking lane. Use a controlled familiar load.','Solo personas avanzadas que conocen el movimiento: pide al entrenador revisar altura del soporte, cierres, posición de barra en la espalda alta y carril. Usa una carga conocida y controlada.','advanced']
  ]){add('lunge',{id,name:L(name,esName),demo:id==='walkingBarbell'?'walkingBarbell':id==='walkingDumbbell'?'walkingDumbbell':'walkingBody',equipment:gear,minLevel:min,setup:L(setup,esSetup),steps:walkingSteps,
    purpose:L('Build unilateral leg strength and control while moving. General support for boxing, not a proven punch-power exercise.','Desarrolla fuerza unilateral y control de piernas al desplazarte. Apoyo general al boxeo, no un ejercicio probado para aumentar la potencia del golpe.'),
    cues:pairList(['Keep the trunk steady and feet on separate tracks. Leave good repetitions in reserve.','Train the lunge here; practise boxing steps separately with your coach.'],['Mantén el tronco estable y los pies en líneas separadas. Deja repeticiones buenas en reserva.','Entrena aquí la zancada; practica los pasos de boxeo por separado con tu entrenador.']),
    avoid:pairList(['Do not punch, twist the loaded trunk, jump or turn abruptly while carrying weights.','Switch to a stationary split squat if space or balance is insufficient.'],['No golpees, gires el tronco cargado, saltes ni gires bruscamente con pesas.','Cambia a sentadilla dividida estática si falta espacio o equilibrio.']),
    doseOverride:{sets:2,reps:'6 each leg',seconds:null,rest:120},source:source(id==='walkingBarbell'?barURL:lungeURL,L('Walking-lunge technique and loading','Técnica y carga de zancadas caminando'))});V[id]={id:'mAgbXQdd4LM',provider:'PureGym',title:L('Walking-lunge mechanics','Mecánica de zancadas caminando'),url:'https://www.youtube.com/watch?v=mAgbXQdd4LM',note:L('The video teaches bodyweight stepping. For dumbbells or a barbell, also follow this guide’s loading setup and have a coach check your technique. Do not copy the publisher’s workout dose.','El video enseña pasos con peso corporal. Con mancuernas o barra, sigue también la preparación de carga de esta guía y pide revisión técnica. No copies la dosis de entrenamiento del editor.')};}
  add('squat',{id:'bodySquat',name:L('Bodyweight squat','Sentadilla con peso corporal'),demo:'bodySquat',equipment:['floor'],setup:L('Stand with feet at a comfortable width and arms forward for balance.','Coloca los pies a una anchura cómoda y los brazos al frente para equilibrarte.'),doseOverride:{sets:2,reps:'8 reps',seconds:null,rest:120}});V.bodySquat={...V.squat,note:L('Use the squat pattern without the kettlebell or dumbbell shown. Keep a comfortable range.','Usa el patrón de sentadilla sin la pesa rusa o mancuerna mostrada. Mantén un rango cómodo.')};
  for(const [id,name,esName,demo,gear,setup,esSetup] of [
    ['wallPushup','Wall push-up','Flexión contra la pared','wallPushup',['floor'],'Place hands on a solid wall at chest height; step back to a comfortable incline.','Coloca manos en una pared sólida a altura del pecho; retrocede hasta una inclinación cómoda.'],
    ['inclineStrengthPushup','Controlled incline push-up','Flexión inclinada controlada','inclinePushup',['bench','floor'],'Place hands on a secured stable bench. Keep hands planted and work slowly.','Coloca manos sobre un banco estable asegurado. Mantén las manos apoyadas y trabaja despacio.']
  ]){add('pushup',{id,name:L(name,esName),demo,equipment:gear,setup:L(setup,esSetup)});V[id]={...V.pushup,note:L('The height differs. Use the wall or secured bench specified by your guide; move under control, with hands planted.','La altura difiere. Usa la pared o banco asegurado de tu guía; muévete con control y las manos apoyadas.')};}
  add('bandRow',{id:'cableRow',name:L('Seated cable row','Remo sentado en polea'),demo:'cableRow',equipment:['cable'],setup:L('Use a seated-row station with secure foot support. Sit tall, knees softly bent and grip comfortable.','Usa estación de remo sentado con apoyo de pies seguro. Siéntate erguido, rodillas suaves y agarre cómodo.'),steps:pairList(['Brace and keep your torso still.','Pull elbows toward your hips without leaning back.','Return the handle slowly without rounding your back.'],['Estabiliza y mantén el tronco inmóvil.','Lleva codos hacia las caderas sin inclinarte hacia atrás.','Devuelve el agarre lentamente sin redondear la espalda.']),source:source('https://www.nasm.org/workout-exercise-guidance',L('NASM exercise library','Biblioteca de ejercicios de NASM'))});
  add('hinge',{id:'bodyHinge',name:L('Bodyweight hip hinge','Bisagra de cadera con peso corporal'),demo:'bodyHinge',equipment:['floor'],setup:L('Stand tall with soft knees and hands on your hips. Practise the hinge without weights.','Ponte erguido con rodillas suaves y manos en caderas. Practica la bisagra sin pesas.'),doseOverride:{sets:2,reps:'8 reps',seconds:null,rest:120}});V.bodyHinge={...V.hinge,note:L('Rehearse without the dumbbells shown; keep the hip-hinge pattern and a comfortable range.','Ensaya sin las mancuernas mostradas; conserva la bisagra de cadera y un rango cómodo.')};
  add('deadbug',{id:'birdDog',name:L('Bird dog','Bird dog en cuadrupedia'),demo:'birdDog',equipment:['mat'],setup:L('Start on hands and knees, hands below shoulders and knees below hips.','Empieza con manos y rodillas apoyadas, manos bajo hombros y rodillas bajo caderas.'),steps:pairList(['Brace gently without holding your breath.','Reach one arm and the opposite leg away while keeping hips level.','Return slowly and alternate sides; start with one limb if balance is difficult.'],['Estabiliza suavemente sin contener la respiración.','Extiende un brazo y la pierna contraria manteniendo las caderas niveladas.','Vuelve despacio y alterna lados; empieza con una extremidad si cuesta equilibrarte.']),purpose:L('Resist trunk rotation and extension during opposite-limb movement.','Resiste la rotación y extensión del tronco al mover extremidades opuestas.'),cues:pairList(['Keep the back neutral and move slowly.'],['Mantén la espalda neutra y muévete despacio.']),avoid:pairList(['Do not arch or twist to lift the leg higher.'],['No arquees ni gires para elevar más la pierna.']),source:source('https://www.nasm.org/resource-center/exercise-library/bird-dog',L('NASM bird-dog technique','Técnica del bird dog de NASM'))});
  V.birdDog={id:'ZdAHe9_HeEw',provider:'NASM',title:L('Bird-dog demonstration','Demostración del bird dog'),url:'https://www.youtube.com/watch?v=ZdAHe9_HeEw',note:L('Move slowly and keep your pelvis still. Follow the app dose, not extra repetitions in the video.','Muévete despacio y mantén la pelvis inmóvil. Sigue la dosis de la app, sin añadir repeticiones del video.')};
  add('sidePlank',{id:'kneeSidePlank',name:L('Kneeling side plank','Plancha lateral con rodillas apoyadas'),demo:'kneeSidePlank',setup:L('Lie on your side with knees bent; place your elbow beneath your shoulder.','Túmbate de lado con rodillas flexionadas; coloca codo bajo hombro.'),steps:pairList(['Brace gently and lift hips while supported on forearm and knees.','Keep shoulder, hips and knees aligned while breathing normally.','Lower with control and repeat on the other side.'],['Estabiliza suavemente y eleva caderas apoyándote en antebrazo y rodillas.','Mantén hombro, caderas y rodillas alineados mientras respiras normalmente.','Baja con control y repite del otro lado.']),doseOverride:{sets:2,reps:'15 seconds each side',seconds:15,rest:60}});V.kneeSidePlank={...V.sidePlank,note:L('Use bent knees on the floor rather than the full leg position shown. Keep the shoulder above the elbow.','Apoya rodillas flexionadas en el suelo en vez de la posición de piernas extendidas mostrada. Mantén hombro sobre codo.')};
  add('sidePlank',{id:'frontPlank',name:L('Forearm plank','Plancha en antebrazos'),demo:'frontPlank',setup:L('Face down with forearms supported, elbows beneath shoulders; use knees or toes.','Colócate boca abajo con antebrazos apoyados y codos bajo hombros; usa rodillas o puntas de pies.'),purpose:L('Control trunk extension with a steady position and normal breathing.','Controla la extensión del tronco con postura estable y respiración normal.'),steps:pairList(['Brace gently and lift hips into a straight shoulder-to-hip line.','Hold without sagging or holding your breath; shorten the lever by using knees.','Lower to rest before position deteriorates.'],['Estabiliza suavemente y eleva caderas formando una línea de hombros a caderas.','Mantén sin hundirte ni contener el aire; acorta la palanca apoyando rodillas.','Baja para descansar antes de perder la postura.']),cues:pairList(['Choose a position you can hold while breathing.'],['Elige una postura que puedas mantener respirando.']),avoid:pairList(['Do not force a long hold when the lower back arches.'],['No fuerces una postura larga si se arquea la zona lumbar.']),doseOverride:{sets:2,reps:'20 seconds',seconds:20,rest:60},source:source(coreURL,L('NSCA trunk-training concepts','Conceptos de entrenamiento del tronco de NSCA'))});
  add('sidePlank',{id:'suitcaseCarry',minLevel:'intermediate',name:L('Light suitcase carry','Paseo con mancuerna a un lado'),demo:'suitcaseCarry',equipment:['dumbbells','walkSpace','floor'],purpose:L('Resist sideways trunk bending while walking with an uneven light load.','Resiste la inclinación lateral del tronco al caminar con carga ligera asimétrica.'),setup:L('Hold one light dumbbell at your side. Confirm a clear lane and keep the free arm relaxed.','Sujeta una mancuerna ligera a un lado. Confirma carril despejado y relaja el brazo libre.'),steps:pairList(['Stand tall without leaning toward or away from the weight.','Take short controlled steps and breathe normally.','Put the weight down safely, rest and repeat with the other hand.'],['Ponte erguido sin inclinarte hacia la carga ni alejarte de ella.','Da pasos cortos controlados y respira normalmente.','Deja la carga de forma segura, descansa y repite con la otra mano.']),cues:pairList(['Use a light load that allows a level pelvis.'],['Usa una carga ligera que permita mantener pelvis nivelada.']),avoid:pairList(['Do not shrug, sprint or continue when posture changes.'],['No encogas hombros, corras ni continúes si cambia la postura.']),doseOverride:{sets:2,reps:'20 seconds each side',seconds:20,rest:60},source:source(coreURL,L('NSCA trunk-training concepts','Conceptos de entrenamiento del tronco de NSCA'))});
  add('bike',{id:'easyRower',name:L('Easy rowing','Remo aeróbico suave'),demo:'rower',equipment:['rower'],setup:L('Ask gym staff to check foot straps and a comfortable resistance. Start gently.','Pide al personal revisar correas de pies y resistencia cómoda. Empieza suavemente.'),steps:pairList(['Drive smoothly with legs, then hips, then arms.','Recover arms first, then hips, then bend knees; keep the back neutral.','Keep a conversational pace throughout the displayed time.'],['Impúlsate suavemente con piernas, después caderas y brazos.','Recupera primero brazos, después caderas y rodillas; mantén espalda neutra.','Mantén un ritmo que permita conversar durante el tiempo mostrado.']),source:source('https://www.concept2.com/training/rowing-technique',L('Concept2 rowing technique','Técnica de remo de Concept2'))});
  for(const [id,name,esName,steps,esSteps] of [
    ['techFootwork','Stance and footwork practice','Práctica de postura y desplazamientos',['Keep a coach-taught stance and guard.','Step forward, backward and sideways without crossing feet.','Pause and reset balance; practise both directions slowly.'],['Mantén postura y guardia enseñadas por el entrenador.','Da pasos al frente, atrás y a los lados sin cruzar pies.','Pausa y recupera equilibrio; practica ambas direcciones despacio.']],
    ['techDefense','Defence and reset practice','Práctica de defensa y recuperación',['Use only slips or blocks already taught by your coach.','Rehearse small controlled movements with eyes forward.','Reset your stance and guard after each action.'],['Usa solo esquivas o bloqueos ya enseñados por tu entrenador.','Ensaya movimientos pequeños controlados mirando al frente.','Recupera postura y guardia después de cada acción.']],
    ['techJab','Jab and guard practice','Práctica de jab y guardia',['Set your coach-taught stance, relaxed shoulders and guard.','Rehearse a relaxed jab; return the hand to guard.','Add an easy stance step only if your coach has taught the combination.'],['Adopta postura enseñada, hombros relajados y guardia.','Ensaya un jab relajado; devuelve la mano a la guardia.','Añade un paso suave solo si el entrenador enseñó esa combinación.']]
  ]){add('shadow',{id,name:L(name,esName),steps:pairList(steps,esSteps),demo:'shadow',purpose:L('Practise one coach-taught boxing skill without fatigue or weighted punches.','Practica una habilidad de boxeo enseñada sin fatiga ni golpes con pesas.')});V[id]={...V.shadow,note:L('The video covers broader basics. Practise only the skill named in this slot and taught by your coach.','El video cubre fundamentos más amplios. Practica solo la habilidad de este bloque enseñada por tu entrenador.')};}
  for(const [id,name,esName,gear,demo,steps,esSteps] of [
    ['cooldownWalk','Easy walking cooldown','Vuelta a la calma caminando',['walkSpace'],'walk',['Walk slowly for the displayed 3 minutes.','Let breathing settle naturally without forcing deep breaths.','Check how legs and shoulders feel before leaving.'],['Camina despacio durante los 3 minutos mostrados.','Deja que la respiración se calme sin forzar inspiraciones profundas.','Comprueba cómo sientes piernas y hombros antes de salir.']],
    ['cooldownMobility','Gentle mobility cooldown','Vuelta a la calma con movilidad',['floor'],'warmup',['Move ankles, hips and shoulders slowly through comfortable ranges.','Breathe normally and keep all movements easy.','Finish within the displayed 3 minutes; do not force stretching.'],['Mueve tobillos, caderas y hombros despacio en rangos cómodos.','Respira normalmente y mantén todos los movimientos suaves.','Termina dentro de los 3 minutos mostrados; no fuerces estiramientos.']]
  ]){add('cooldown',{id,name:L(name,esName),equipment:gear,demo,steps:pairList(steps,esSteps)});V[id]={...V[id==='cooldownWalk'?'walk':'warmup'],note:L('Use this as an easy recovery component and follow the written steps. This is not additional conditioning.','Usa esto como componente suave de recuperación y sigue los pasos escritos. No es acondicionamiento adicional.')};}
  const groups={
    warmup:['warmup','warmRope','warmBike','warmShadow'],
    jump:['jump','rotation','chestThrow','fastPushup'],rotation:['rotation','chestThrow','fastPushup','jump'],chestThrow:['chestThrow','rotation','fastPushup','jump'],
    squat:['squat','bodySquat','splitSquat','stepup','walkingBody','walkingDumbbell'],
    press:['press','pushup','inclineStrengthPushup','wallPushup'],
    row:['row','bandRow','cableRow','pulldown'],pulldown:['pulldown','row','bandRow','cableRow'],
    hinge:['hinge','bridge','bodyHinge'],
    lunge:['lunge','walkingBody','walkingDumbbell','walkingBarbell','splitSquat','stepup'],
    pallof:['pallof','bandPallof','deadbug','birdDog'],
    sidePlank:['sidePlank','kneeSidePlank','frontPlank','suitcaseCarry','deadbug'],
    sled:['sled','ropes','bikeIntervals','marchIntervals','stepup','splitSquat'],
    ropes:['ropes','bikeIntervals','marchIntervals','sled'],
    bike:['bike','walk','easyMarch','easyRower'],
    shadow:['shadow','techFootwork','techDefense','techJab'],
    cooldown:['cooldown','cooldownWalk','cooldownMobility']
  };
  const roles={warmup:L('Warm-up','Calentamiento'),jump:L('Explosive work','Trabajo explosivo'),rotation:L('Explosive work','Trabajo explosivo'),chestThrow:L('Explosive work','Trabajo explosivo'),squat:L('Leg resistance','Resistencia de piernas'),press:L('Pushing resistance','Resistencia de empuje'),row:L('Pulling resistance','Resistencia de tracción'),pulldown:L('Pulling resistance','Resistencia de tracción'),hinge:L('Hip and posterior-chain strength','Fuerza de cadera y cadena posterior'),lunge:L('Single-leg strength','Fuerza unilateral de piernas'),pallof:L('Abs: rotation and extension control','Abdominales: control de rotación y extensión'),sidePlank:L('Abs: lateral and extension control','Abdominales: control lateral y de extensión'),sled:L('Conditioning','Acondicionamiento'),ropes:L('Conditioning','Acondicionamiento'),bike:L('Easy aerobic work','Trabajo aeróbico suave'),shadow:L('Boxing technique','Técnica de boxeo'),cooldown:L('Cooldown','Vuelta a la calma')};
  const rank={rookie:0,intermediate:1,advanced:2};
  function options(original){return (groups[original]||[original,...(by(original)?.alternatives||[])]).map(by).filter(Boolean);}
  function allowed(ex,level){return ex?.category!=='Power'||level!=='rookie' ? (rank[ex?.minLevel||'rookie']<=rank[level||'intermediate']) : false;}
  function validSelection(original,id,level){return options(original).some(e=>e.id===id&&allowed(e,level));}
  function prescription(item,ex){
    if(ex.id===item.exercise)return item;
    const template=D.days.flatMap(d=>d.items).find(i=>i.exercise===ex.id);
    // Keep the original logging slot, but use the chosen movement's units and progression.
    const d=template?{...item,...template,exercise:item.exercise,conditioning:item.conditioning||false}:{...item};
    if(!template&&['Strength','Trunk control'].includes(ex.category)){d.seconds=null;d.progression={};d.techniqueDose=null;}
    if(ex.doseOverride)Object.assign(d,ex.doseOverride);
    return d;
  }
  const sourceEntry=(id,url,title,esTitle,finding,esFinding,application,esApplication,limit,esLimit)=>({id,type:'practice',url,citation:'Professional guidance · consulted 8 October 2026',title:L(title,esTitle),design:L('Professional education or technique guidance; not a trial of this app’s choices.','Orientación profesional o técnica; no es un ensayo de las opciones de esta app.'),finding:L(finding,esFinding),application:L(application,esApplication),limit:L(limit,esLimit)});
  E.sources.push(
    sourceEntry('warmup-options',warmURL,'Dynamic warm-ups and movement rehearsal','Calentamiento dinámico y ensayo de movimientos','Warm-ups combine gentle general activity with preparation for the intended movements.','El calentamiento combina actividad general suave y preparación para los movimientos previstos.','Each warm-up option retains easy activity, mobility and rehearsal within the existing 8-minute block.','Cada opción conserva actividad suave, movilidad y ensayo dentro del bloque existente de 8 minutos.','The exact sequence is app programming, not a validated boxing warm-up protocol.','La secuencia exacta es programación de la app, no un protocolo de calentamiento de boxeo validado.'),
    sourceEntry('skipping-guide',ropeURL,'Basic skipping mechanics','Mecánica básica de salto con cuerda','A light rope, relaxed shoulders, wrist rotation and low jumps support basic skipping technique.','Una cuerda ligera, hombros relajados, giro de muñecas y saltos bajos orientan la técnica básica.','Easy skipping can replace the warm-up’s pulse-raising component; marching is the fallback.','El salto suave puede sustituir la parte inicial del calentamiento; la marcha es la alternativa.','Does not prove improved boxing footwork or punch force, or validate this exact warm-up dose.','No demuestra mejoras de desplazamientos o fuerza del golpe, ni valida esta dosis exacta.'),
    sourceEntry('lunge-options',lungeURL,'Walking lunges and load choices','Zancadas caminando y opciones de carga','Walking lunges train legs and challenge balance as weight shifts between steps.','Las zancadas caminando entrenan piernas y desafían el equilibrio al cambiar el apoyo.','Bodyweight precedes dumbbells; the barbell variant is reserved for familiar Advanced users with checked setup.','El peso corporal precede a mancuernas; la variante con barra se reserva a Avanzados que conocen el ejercicio y revisan su preparación.','Technique guidance does not establish punch-power transfer. The app does not copy near-failure doses from the publisher.','La orientación técnica no demuestra transferencia a la potencia del golpe. La app no copia las dosis próximas al fallo del editor.'),
    sourceEntry('core-roles',coreURL,'Core training by movement role','Entrenamiento del tronco según su función','Sport programming considers trunk stability, force transfer and different planes of movement.','La programación deportiva considera estabilidad del tronco, transferencia de fuerza y distintos planos de movimiento.','Offer rotation-control, extension-control and side-support options; distinguish timed holds from repetitions.','Ofrece control de rotación, de extensión y apoyo lateral; distingue posturas cronometradas y repeticiones.','These alternatives are not mechanically identical. Their exact doses and effects on boxing have not been validated together.','Estas alternativas no son mecánicamente idénticas. Sus dosis exactas y efectos en boxeo no se han validado en conjunto.')
  );
  E.groups.push({title:L('Movement choices, warm-ups and walking lunges','Opciones de movimientos, calentamientos y zancadas caminando'),ids:['acsm','warmup-options','skipping-guide','lunge-options','core-roles'],exercises:D.exercises.map(e=>e.id)});
  const trunkRoles={
    pallof:L('Resist rotation','Resistir la rotación'),bandPallof:L('Resist rotation','Resistir la rotación'),
    deadbug:L('Control extension during limb movement','Controlar la extensión al mover extremidades'),
    birdDog:L('Resist rotation and extension','Resistir la rotación y la extensión'),
    frontPlank:L('Resist extension','Resistir la extensión'),
    sidePlank:L('Resist lateral bending','Resistir la inclinación lateral'),kneeSidePlank:L('Resist lateral bending','Resistir la inclinación lateral'),
    suitcaseCarry:L('Resist lateral bending while walking','Resistir la inclinación lateral al caminar')
  };
  for(const [en,es] of [
    ['Choose your exercises','Elige tus ejercicios'],['Choose your movement','Elige tu movimiento'],['Choose movement','Elegir movimiento'],
    ['Pick one movement per slot. Choices replace work; they do not add exercises. The plan recalculates after each choice.','Elige un movimiento por bloque. Las opciones sustituyen trabajo; no añaden ejercicios. El plan se recalcula después de cada elección.'],
    ['Options depend on level and confirmed equipment. A short session may omit a slot. Its choice stays saved for a longer session.','Las opciones dependen del nivel y equipo confirmado. Una sesión corta puede omitir un bloque. Su elección queda guardada para una sesión más larga.'],
    ['Different level','Otro nivel'],['Already in this session','Ya está en esta sesión'],['Confirm gear','Confirmar equipo'],
    ['Omitted for level, time or repeated movement.','Omitido por nivel, tiempo o movimiento repetido.'],['Completed slot is locked.','El bloque completado está bloqueado.'],['One option replaces this slot.','Una opción sustituye este bloque.'],
    ['View guide ↗','Ver guía ↗'],['Movement updated. Check its dose and guide.','Movimiento actualizado. Revisa su dosis y guía.'],
    ['Power options have different leg, rotation and pushing roles. Core options have different rotation, extension and side-support roles. They are not identical substitutes.','Las opciones de potencia tienen funciones distintas de piernas, rotación y empuje. Las opciones del tronco tienen funciones distintas de rotación, extensión y apoyo lateral. No son sustitutos idénticos.'],
    ['SAME TRAINING SLOT','MISMO BLOQUE DE ENTRENAMIENTO'],['CONTROL','CONTROLA'],['Trunk role','Función del tronco']
  ])L(en,es);
  const video=(id,provider,title,esTitle,note,esNote)=>({id,provider,title:L(title,esTitle),note:L(note,esNote),url:'https://www.youtube.com/watch?v='+id});
  V.warmRope=video('yXIy2ueZtmY','PureGym','Basic single-under skipping','Salto básico con cuerda','Use easy low skips only, with marching breaks. Then follow the mobility and rehearsal steps; this video is not the whole warm-up.','Usa solo saltos bajos suaves con pausas de marcha. Después sigue los pasos de movilidad y ensayo; el video no muestra todo el calentamiento.');
  V.cableRow=video('lJoozxC0Rns','PureGym','Seated cable row','Remo sentado en polea','Keep your torso steady and use a controlled load. Follow the app sets and rests, not a workout dose from the publisher.','Mantén el tronco estable y usa carga controlada. Sigue las series y descansos de la app, no una dosis de entrenamiento del editor.');
  by('cableRow').source=source('https://www.puregym.com/exercises/back/rows/seated-cable-row/',L('PureGym seated cable-row technique','Técnica de remo sentado en polea de PureGym'));
  V.frontPlank=video('mwlp75MS6Rg','NASM','Forearm plank','Plancha en antebrazos','Use knees or toes as your guide allows, breathe normally and end the hold before posture changes. Follow the displayed time.','Usa rodillas o puntas de pies según tu guía, respira normalmente y termina antes de perder postura. Sigue el tiempo mostrado.');
  by('frontPlank').source=source('https://www.nasm.org/resource-center/exercise-library/plank',L('NASM plank technique','Técnica de plancha de NASM'));
  V.suitcaseCarry=video('pm0snKjqXrI','IFAST · Zach Moore','Suitcase-carry mechanics','Mecánica del paseo con carga a un lado','The coach demonstrates a kettlebell. Use the light dumbbell in your guide and the displayed time on each side; do not copy heavy loads or the publisher’s distances.','El entrenador muestra una pesa rusa. Usa la mancuerna ligera de tu guía y el tiempo mostrado por lado; no copies cargas pesadas ni distancias del editor.');
  V.easyRower=video('4zWu1yuJ0_g','Concept2','Rowing stroke sequence','Secuencia de la remada','Learn the leg, hip and arm sequence. Keep this slot easy and conversational; do not copy racing pace or extra intervals.','Aprende la secuencia de piernas, caderas y brazos. Mantén este bloque suave y a ritmo de conversación; no copies ritmo de competición ni intervalos adicionales.');
  by('techFootwork').demo='footwork';by('techDefense').demo='defence';
  by('bodyHinge').steps[0]=L('Brace gently with hands resting on your hips; keep knees softly bent.','Estabiliza suavemente con manos en las caderas; mantén rodillas ligeramente flexionadas.');
  by('cableRow').cues=[L('Use a load you can pull without rocking your torso.','Usa una carga que puedas tirar sin balancear el tronco.')];
  by('cableRow').avoid=[L('Do not lean back to move the handle or let the stack slam.','No te inclines hacia atrás para mover el agarre ni dejes caer los discos de la máquina.')];
  by('cableRow').doseOverride.notes=L('Controlled horizontal pulling; it differs from a vertical pulldown.','Tracción horizontal controlada; difiere de un jalón vertical.');
  D.equipment.push({id:'pushWall',name:L('Solid wall for wall push-ups','Pared sólida para flexiones')});
  D.equipment.push({id:'cableRowStation',name:L('Seated cable-row station with foot supports','Estación de remo sentado en polea con apoyos de pies')});
  by('cableRow').equipment=['cableRowStation'];
  by('wallPushup').equipment=['pushWall','floor'];
  function cleanEquipmentChecks(value) {
    const out={};
    if(!value || typeof value!=='object' || Array.isArray(value))return out;
    for(const [key,record] of Object.entries(value)){
      if(!/^[1-8]:(mon|tue|wed|thu|fri|sat|sun):[a-zA-Z]+$/.test(key)||!record||typeof record!=='object')continue;
      const ex=options(key.split(':')[2]).find(ex=>ex.id===record.exercise);
      if(!ex || !record.items || typeof record.items!=='object' || Array.isArray(record.items))continue;
      const items={};
      for(const id of ex.equipment || [])if(typeof record.items[id]==='boolean')items[id]=record.items[id];
      out[key]={exercise:ex.id,items};
    }
    return out;
  }
  window.RoundworkChoices={groups,roles,trunkRoles,options,allowed,validSelection,prescription,pairs,cleanEquipmentChecks};
  L('Done','Hecho');
  L('Equipment ready','Equipo disponible');
  L('Confirm for this exercise only.','Confirma solo para este ejercicio.');
  L('Equipment checklist','Lista de equipo');
  L('Select the items available for this exercise.','Selecciona los elementos disponibles para este ejercicio.');
  L('Equipment','Equipo');
  L('I have all the equipment listed above.','Tengo todo el equipo indicado arriba.');
  L('Confirm the listed equipment on this card before training.','Confirma el equipo indicado en esta tarjeta antes de entrenar.');
  window.ROUNDWORK_CHOICES_TEXT=pairs.map(p=>p[0]);
})();
