/* Roundwork: conservative starting prescriptions; reviewed 5 October 2026. */
window.BOXING_DATA = (() => {
const sources = {
 power:{label:'Boxing Science · power exercises',url:'https://boxingscience.co.uk/improve-punching-power/'},
 rotation:{label:'Boxing Science · rotational power',url:'https://boxingscience.co.uk/rotational-power-exercises/'},
 chest:{label:'Boxing Science · strength and power',url:'https://boxingscience.co.uk/complex-training-for-boxing/'},
 jump:{label:'ACE · squat jump guide',url:'https://www.acefitness.org/resources/everyone/exercise-library/222/squat-jump/'},
 squat:{label:'NASM · goblet squat guide',url:'https://www.nasm.org/resource-center/blog/training/how-to-perform-goblet-squats'},
 press:{label:'ACE · chest press guide',url:'https://www.acefitness.org/resources/everyone/exercise-library/19/chest-press/'},
 row:{label:'ACE · supported single-arm row',url:'https://www.acefitness.org/resources/everyone/exercise-library/126/single-arm-row/'},
 hinge:{label:'NASM · dumbbell Romanian deadlift',url:'https://www.nasm.org/resource-center/exercise-library/dumbbell-romanian-deadlift'},
 plank:{label:'NASM · side plank guide',url:'https://www.nasm.org/resource-center/exercise-library/side-plank'},
 sled:{label:'NSCA · sled push video guide',url:'https://www.nsca.com/education/videos/bridge-series/bridge-modifying-the-sled-push-for-tactical-athletes-with-steve-morgan/'},
 ropes:{label:'ACE · battle rope guide',url:'https://www.acefitness.org/continuing-education/certified/march-2023/8267/battle-rope-ready-a-research-based-workout/'},
 shadow:{label:'England Boxing · shadowboxing themes',url:'https://www.englandboxing.org/news_articles/shadow-boxing-drills-with-mick-driscoll/'},
 library:{label:'ACE · exercise reference library',url:'https://www.acefitness.org/resources/everyone/exercise-library/'},
 cardio:{label:'Boxing Science · conditioning principles',url:'https://boxingscience.co.uk/conditioning-for-boxing-the-boxing-science-method/?wmc-currency=EUR'}
};
const equipment=[['dumbbells','Dumbbells'],['bench','Stable exercise bench'],['medicineBall','Light throwing medicine ball'],['throwWall','Wall approved for ball throws'],['sled','Push sled'],['sledLane','Clear, approved sled lane'],['ropes','Battle ropes with secure anchor'],['bike','Stationary bike'],['rower','Rowing machine'],['walkSpace','Clear walking / jogging space'],['floor','Clear non-slip exercise floor'],['mat','Exercise mat or padded floor'],['cable','Cable station'],['pulldown','Lat pulldown machine'],['bands','Resistance bands'],['bandAnchor','Suitable secure band anchor'],['step','Stable low exercise step']].map(([id,name])=>({id,name}));
const E=(id,name,category,eq,demo,purpose,setup,steps,cues,avoid,source,alternatives=[],extra={})=>({id,name,category,equipment:eq,demo,purpose,setup,steps,cues,avoid,source,alternatives,...extra});
const exercises=[
E('warmup','Prepare to move','Preparation',['floor'],'warmup','Raise temperature and rehearse today’s movements.','Clear a small area. Start gently.', ['March or walk easily for 3 minutes.','Move ankles, hips and shoulders through comfortable ranges for 2 minutes.','Rehearse squats, hinges and today’s throws without load; do light ramp-up sets before lifting.'],['Build effort gradually.','Practice landings before jumping.'],['Do not begin with maximal jumps or heavy lifts.'],sources.library),
E('jump','Reset vertical jump','Power',['floor'],'jump','Practise rapid leg force and a controlled landing.','Feet around hip width; clear overhead and landing space.', ['Stand tall, then dip slightly at hips and knees.','Swing arms and jump upward with a quick, coordinated drive.','Land softly on both feet, let knees bend, then fully reset.'],['Start with comfortable jump height.','Rest 90–120 seconds between sets.'],['Stop when landing quality or height declines.','No loaded or depth jumps in this block.'],sources.jump,[],{substitutionNote:'If jumping is uncomfortable, skip this power drill; a slow squat is not an equivalent power substitute.'}),
E('rotation','Rotational medicine-ball throw','Power',['medicineBall','throwWall','floor'],'rotationalThrow','Practise producing force quickly through legs and trunk.','Use a light throwing ball, often 1–3 kg; stand side-on to an approved wall at a safe distance.', ['Hold the ball at the outside hip with both hands; soften knees.','Turn feet and hips with the torso and throw toward the wall.','Let the ball settle safely; reset fully and repeat both sides.'],['Have a trainer demonstrate your first session.','Choose speed over a heavy ball.'],['Do not twist only through the lower back.','Do not catch a fast rebound close to your face.'],sources.rotation,['fastPushup'],{substitutionNote:'A fast incline push-up trains upper-body pushing speed; it does not reproduce rotational throwing.'}),
E('chestThrow','Medicine-ball chest pass','Power',['medicineBall','throwWall','floor'],'chestThrow','Practise a fast two-arm pushing action.','Use a light throwing ball and an approved wall with clear rebound space.', ['Stand balanced, knees soft, ball in front of chest.','Brace and drive the ball forward rapidly with both hands.','Allow a safe rebound, collect the ball and reset your stance.'],['Keep each repetition fast.','Use a trainer’s demonstration for ball and wall setup.'],['Do not turn this into a continuous fatigue circuit.'],sources.chest,['fastPushup']),
E('squat','Goblet squat','Strength',['dumbbells','floor'],'squat','Maintain leg strength with a focused workload.','Hold one dumbbell close to the chest; feet at a comfortable width.', ['Stand tall, brace gently, distribute pressure across each foot.','Bend hips and knees together to a comfortable depth.','Push the floor away and return to standing under control.'],['Keep approximately 3 good repetitions in reserve.','Use a familiar squat variation if preferred.'],['Do not chase depth by rounding your back.'],sources.squat,['splitSquat']),
E('press','Dumbbell bench press','Strength',['dumbbells','bench'],'benchPress','Train pushing strength without exhausting the shoulders.','Lie on a stable bench with feet supported and dumbbells under control.', ['Start with dumbbells above the chest and wrists stacked.','Lower slowly with elbows at a comfortable angle to the torso.','Press up smoothly, then repeat without bouncing.'],['Finish with 3 repetitions in reserve.','Keep feet and upper back stable.'],['Avoid painful depth or flared, uncontrolled elbows.'],sources.press,['pushup']),
E('row','Supported one-arm row','Strength',['dumbbells','bench'],'row','Balance pressing with controlled upper-back pulling.','Support one hand and knee on a stable bench; hold a dumbbell in the other hand.', ['Let the working arm hang while keeping the torso stable.','Pull the elbow toward your hip without turning your torso.','Lower slowly to the start; complete both sides.'],['Use a comfortable neutral spine.','Keep 3 repetitions in reserve.'],['Do not jerk the weight upward.'],sources.row,['bandRow'],{substitutionNote:'No band or dumbbell setup? Leave this slot unfilled today. Bodyweight pushing is not a comparable pulling substitute.'}),
E('pallof','Pallof press','Trunk control',['cable','floor'],'pallof','Resist unwanted trunk rotation while the arms move.','Set a cable around chest height; stand side-on with a manageable load.', ['Hold the handle at your chest with both hands.','Press straight forward and pause 1–2 seconds without turning.','Return slowly; repeat facing the other direction.'],['Breathe normally.','Keep ribs stacked over pelvis.'],['Do not use enough load to twist your stance.'],sources.library,['bandPallof','deadbug']),
E('hinge','Dumbbell Romanian deadlift','Strength',['dumbbells','floor'],'hinge','Train hip-hinge strength through hamstrings and glutes.','Stand with dumbbells close to thighs, knees softly bent.', ['Brace and keep the weights near your legs.','Push hips backward with a long neutral spine until a comfortable hamstring stretch.','Drive through the feet and bring hips forward to stand tall.'],['Depth depends on your mobility.','Keep 3 repetitions in reserve.'],['Do not round the back or lean backward at the top.'],sources.hinge,['bridge']),
E('lunge','Reverse lunge','Strength',['dumbbells','floor'],'lunge','Train leg strength and balance one side at a time.','Use light dumbbells or bodyweight; leave room to step backward.', ['Stand balanced with feet at hip width.','Step one foot back and lower under control, front foot flat.','Push through the front leg to return; repeat both sides.'],['Start light before Thursday coaching.','Use a comfortable step length.'],['Do not slam the rear knee down.'],sources.library,['splitSquat']),
E('pulldown','Lat pulldown','Strength',['pulldown'],'pulldown','Train vertical upper-body pulling strength.','Set thigh pad securely and choose a manageable load.', ['Sit tall and grip the bar slightly wider than shoulders.','Pull elbows down as the bar approaches the upper chest.','Return overhead slowly without lifting off the seat.'],['Keep neck relaxed.','Leave 3 good repetitions in reserve.'],['Do not pull behind your head or swing backward.'],sources.library,['bandRow','row'],{substitutionNote:'A row supplies pulling work but changes the direction of loading. With no suitable pulling equipment, skip the slot.'}),
E('sidePlank','Side plank','Trunk control',['mat'],'sidePlank','Train lateral trunk stability.','Lie on your side with elbow under shoulder. Bend knees for the easier version.', ['Stack shoulder over elbow and brace gently.','Lift hips so the supported body forms a straight line.','Hold while breathing, lower slowly, then change sides.'],['Stop before position collapses.','Use the bent-knee version first if needed.'],['Do not hold through shoulder pain.'],sources.plank,['deadbug']),
E('sled','Sled push','Conditioning',['sled','sledLane'],'sled','Add controlled resisted leg drive and work capacity. This is not a direct punch-power test.','Use high handles and a clear 15–20-metre approved lane. Surface friction changes the load greatly.', ['Hold handles firmly, brace and lean forward as a whole body.','Take short driving steps and push smoothly for the prescribed 15–20 metres.','Stop under control and recover fully before the next length.'],['Normal dose: RPE 7/10, no grinding.','First learn the movement with an easy load.'],['Do not improvise by pushing a switched-off treadmill.','No maximal sled sprints in this foundation block.'],sources.sled,['stepup','splitSquat'],{substitutionNote:'Step-ups or split squats provide controlled leg resistance; they do not reproduce the sled’s horizontal force or exact conditioning demand.'}),
E('ropes','Alternating battle-rope waves','Conditioning',['ropes','floor'],'ropes','Train repeated upper-body effort; this is conditioning, not maximal strength.','Check the rope anchor; hold an end in each hand with slack and a comfortable stance.', ['Soften knees, hinge slightly and keep shoulders relaxed.','Move arms up and down alternately to send small waves toward the anchor.','Stop at the work interval and recover with easy breathing.'],['Keep ribs controlled and waves consistent.','Normal dose: 7–8/10 effort, never all-out.'],['Stop if shoulders shrug, lower back arches or technique falls apart.'],sources.ropes,['bikeIntervals','marchIntervals'],{substitutionNote:'Cycling or marching preserves an interval-conditioning slot but loses the ropes’ upper-body emphasis.'}),
E('bike','Easy stationary cycling','Aerobic',['bike'],'bike','Build steady aerobic work capacity without a hard finisher.','Adjust the seat so the knee remains slightly bent at the bottom of the pedal stroke.', ['Begin pedalling at a comfortable resistance.','Settle into an effort where full sentences are easy.','Keep the pace steady, then ease off during the final minutes.'],['Use the talk test, roughly 3–4/10 effort.','Cardio is not a race.'],['If breathing prevents conversation, reduce resistance.'],sources.cardio,['walk','easyMarch']),
E('walk','Easy walk or jog','Aerobic',['walkSpace'],'walk','Build steady aerobic work capacity.','Choose a clear, predictable route or normal powered treadmill.', ['Start walking comfortably.','Increase pace only while you can speak in full sentences.','Maintain an easy rhythm and slow down to finish.'],['Jog only if it is already comfortable for you.'],['Do not add sprints to this easy slot.'],sources.cardio,['bike','easyMarch']),
E('shadow','Purposeful shadowboxing','Technique',['floor'],'shadow','Rehearse coach-taught footwork, balance and combinations.','Use empty hands and a clear floor. Imagine an opponent at a realistic distance.', ['Round 1: stance and small forward, backward and sideways steps.','Round 2: your coach’s jab, return to guard and exit.','Round 3: a familiar combination followed by a defence your coach taught.'],['Keep movements relaxed; reset if balance is lost.','Take 1 minute between rounds.'],['Do not add dumbbells or invent unfamiliar defences.'],sources.shadow),
E('cooldown','Easy cooldown','Recovery',[],'cooldown','Let breathing settle and check how the session felt.','Use a comfortable standing or seated position.', ['Slow down gradually for 2 minutes.','Move or stretch gently within a comfortable range.','Record fatigue and any movement that needs your coach’s feedback.'],['Normal breathing should return gradually.'],['Do not force stretches.'],sources.library),
E('coach','Coached boxing session','Technique',[],'coach','Practise technique and receive feedback from your coach.','Bring the equipment your coach requests; gym gear substitutions do not apply.', ['Tell your coach about your recent training and fatigue.','Follow the session they prescribe, including any supervised partner work.','Ask for one correction to rehearse during the next solo practice.'],['Thursday and Saturday: 45–60 minutes.','Coach determines sparring and competition readiness.'],['Do not add unsupervised sparring as a substitute.'],sources.shadow),
E('rest','Recovery day','Recovery',[],'rest','Recover for the next useful session.','No workout to complete today.', ['Take a comfortable walk if you want to move.','Eat normally, hydrate and make time for sleep.','Check whether soreness or fatigue has resolved before the next session.'],['Aim to feel refreshed, not to earn extra training volume.'],[],sources.library),
E('pushup','Controlled push-up','Strength',['floor'],'pushup','Replace bench pressing with a scalable pushing movement.','Use a wall or stable bench for an incline if floor push-ups are too demanding.', ['Place hands slightly wider than shoulders and align the body.','Lower the chest with elbows at a comfortable angle.','Push back up, keeping the trunk steady.'],['Choose an incline that leaves 3 repetitions in reserve.'],['Avoid sagging hips or painful wrists.'],sources.library,[],{doseOverride:{reps:'6–10 controlled reps',notes:'Choose wall, incline or floor height to leave 3 repetitions in reserve.'}}),
E('fastPushup','Fast incline push-up','Power',['bench','floor'],'pushup','A simple fast pushing alternative when throwing is unavailable.','Use a stable bench braced against movement. Pick an easy incline.', ['Set a straight body position and lower under control.','Push away quickly while keeping hands in contact with the bench.','Reset fully before the next repetition.'],['Keep all repetitions crisp.','No clap or hand release needed.'],['A bench must not slide or tip.'],sources.library,[],{doseOverride:{reps:'3 quick reps',rest:90,notes:'Upper-body speed substitute; rotational throw benefits are not fully reproduced.'},substitutionNote:'If no safe bench is available, skip this power slot rather than improvise an unstable support.'}),
E('splitSquat','Bodyweight split squat','Strength',['floor'],'splitSquat','Provide a controlled equipment-free leg-strength option.','Use a split stance; hold a wall lightly for balance if needed.', ['Stand in a comfortable split stance, both feet facing forward.','Lower vertically with control, keeping the front foot flat.','Push through the front leg to rise; repeat each side.'],['Use a slow 3-second lowering phase if the movement is easy.'],['Keep knee movement comfortable; avoid bouncing.'],sources.library,[],{doseOverride:{sets:2,reps:'6–8 each leg',rest:90,seconds:null,notes:'Controlled strength substitute. Keep 3 good repetitions in reserve; it does not mimic a sled push.'}}),
E('bandRow','Standing band row','Strength',['bands','bandAnchor','floor'],'bandRow','Provide horizontal pulling when machines or dumbbells are unavailable.','Inspect the band and secure it to a suitable chest-height anchor.', ['Hold the band with arms forward and a balanced stance.','Pull elbows back alongside your ribs without leaning.','Return slowly under control.'],['Use tension that permits 8–12 clean repetitions.'],['Do not attach to loose furniture or an unsecured door.'],sources.library,['row'],{doseOverride:{reps:'8–12 controlled reps',notes:'Horizontal pulling substitute, not an identical vertical-pull stimulus.'}}),
E('bandPallof','Band Pallof press','Trunk control',['bands','bandAnchor','floor'],'pallof','Resist trunk rotation with a band.','Inspect and anchor the band at chest height. Stand sideways.', ['Hold the band close to your chest.','Press forward without allowing your torso to turn.','Return slowly and repeat on both sides.'],['Choose light tension first.'],['Do not use an insecure anchor.'],sources.library,['deadbug']),
E('deadbug','Dead bug','Trunk control',['mat'],'deadbug','Equipment-light trunk control through slow arm and leg movement.','Lie on your back, arms up and knees bent above hips.', ['Gently brace and keep the back in a comfortable stable position.','Extend opposite arm and leg only as far as you can control.','Return and alternate sides slowly.'],['Exhale during the reach.'],['Do not arch your back to reach farther.'],sources.library,[],{doseOverride:{sets:2,reps:'6 each side',rest:45,seconds:null,notes:'Trunk-control alternative; not the same anti-rotation or side-support demand.'}}),
E('bridge','Glute bridge','Strength',['mat'],'bridge','A low-load hip-extension alternative when weights are missing.','Lie on your back with knees bent and feet flat.', ['Brace gently with feet around hip width.','Drive through your feet and raise hips to align torso and thighs.','Lower slowly and repeat without arching the back.'],['Pause briefly at the top.'],['Do not push into lower-back extension.'],sources.library,[],{doseOverride:{sets:2,reps:'10–15 reps',rest:60,notes:'Lower-load fallback. This does not replace the full strength stimulus of a loaded Romanian deadlift.'}}),
E('stepup','Low step-up','Strength',['step'],'lunge','Controlled leg work when a sled is unavailable.','Use a stable low exercise step and space to step down safely.', ['Place one whole foot on the step.','Drive through that leg to stand on the step without bouncing.','Step down slowly; complete both sides.'],['Begin with bodyweight.'],['Do not use a chair or unstable box.'],sources.library,['splitSquat'],{doseOverride:{sets:2,reps:'6 each leg',rest:90,seconds:null,notes:'Controlled strength substitute, not a sprint. It does not reproduce sled mechanics.'},demo:'stepup'}),
E('bikeIntervals','Bike intervals','Conditioning',['bike'],'bike','An interval-conditioning substitute for missing battle ropes.','Set the seat and resistance for smooth pedalling.', ['Pedal easily before the first interval.','Increase resistance or cadence for the prescribed work time.','Pedal gently through the recovery time.'],['Keep hard efforts repeatable, about 7/10.'],['No all-out sprints or standing starts.'],sources.cardio,['marchIntervals']),
E('marchIntervals','Brisk marching intervals','Conditioning',[],'warmup','A low-impact, equipment-free conditioning fallback.','Choose a clear spot or hold stable support if balance requires it.', ['Begin with comfortable marching.','Increase arm swing and marching pace for the work interval.','Return to gentle marching during recovery.'],['Adjust pace to breathing.'],['This may be less challenging than ropes; do not add impact just to match fatigue.'],sources.cardio,[],{substitutionNote:'Low-impact fallback; not an equivalent upper-body conditioning stimulus.'}),
E('easyMarch','Easy marching','Aerobic',[],'warmup','An equipment-free option for easy movement.','Find a clear standing area; keep the effort comfortable.', ['Start with small easy marching steps.','Keep a conversational effort and relaxed arm swing.','Slow down gradually to finish.'],['If space and equipment allow, cycling or walking may make sustained aerobic work easier.'],[],sources.cardio,[],{substitutionNote:'A lower-demand fallback; aerobic stimulus depends on your breathing and pace.'})
];
const I=(exercise,sets,reps,rest=60,extra={})=>({exercise,sets,reps,rest,...extra});
exercises.find(e=>e.id==='pallof').source={label:'ACE · standing anti-rotation press',url:'https://www.acefitness.org/resources/everyone/exercise-library/332/standing-anti-rotation-press/'};
exercises.find(e=>e.id==='pulldown').source={label:'ACE · lat pulldown guide',url:'https://www.acefitness.org/resources/everyone/exercise-library/158/seated-lat-pulldown/'};
exercises.find(e=>e.id==='lunge').source={label:'Keele University · exercise demonstrations',url:'https://www.keele.ac.uk/sportatkeele/activekeele/exerciselibrary/'};
exercises.find(e=>e.id==='row').demo='oneArmRow';
exercises.find(e=>e.id==='bikeIntervals').doseOverride={notes:'Pedal at a repeatable 7/10 effort during each work interval; easy pedalling during recovery. This replaces the rope block, not an extra interval session.'};
exercises.find(e=>e.id==='bikeIntervals').techniqueDoseOverride={sets:2,reps:'10 seconds · easy pedalling',seconds:10,rest:60,notes:'Easy familiarisation only, RPE 4–5. Skip if you feel fatigued.'};
exercises.find(e=>e.id==='marchIntervals').doseOverride={notes:'March briskly through each work interval; return to easy marching for recovery. Lower-load conditioning alternative.'};
exercises.find(e=>e.id==='marchIntervals').techniqueDoseOverride={sets:2,reps:'10 seconds · easy marching',seconds:10,rest:60,notes:'Easy movement only; no hard interval work today.'};
exercises.find(e=>e.id==='fastPushup').demo='inclinePushup';
const warm=I('warmup',1,'8–10 minutes',0,{seconds:480});
const cool=I('cooldown',1,'5 minutes',0,{seconds:300});
const power=(id,reps)=>I(id,3,reps,90,{notes:'Reset between repetitions. Stop when speed or landing quality falls.',progression:{4:{sets:3},6:{sets:3},8:{sets:3}}});
const days=[
 {id:'mon',label:'Monday',title:'Power & strength A',minutes:'85–100 min',description:'Explosive work first. Strength next. Sled practice and easy cardio finish the session.',items:[warm,power('jump','3 reps'),power('rotation','3 each side'),I('squat',3,'5 reps',120),I('press',2,'6 reps',120),I('row',2,'8 each side',90),I('pallof',2,'8 each side',45),I('sled',4,'15 metres',120,{conditioning:true,progression:{4:{sets:5},6:{sets:5,reps:'20 metres'},8:{sets:5,reps:'20 metres'}},notes:'RPE 7/10. Choose a load you can push smoothly for the entire distance; stop if speed or posture deteriorates. No extra HIIT finisher.',techniqueDose:{sets:2,reps:'10 metres · easy load',rest:90,notes:'Coach load unknown or hard: easy technique only, RPE 4–5. Skip if legs feel heavy.'}}),I('bike',1,'20 minutes',0,{seconds:1200}),cool]},
 {id:'tue',label:'Tuesday',title:'Skills & conditioning',minutes:'50–65 min',description:'Purposeful shadowboxing, a steady aerobic base and a full intermediate rope block when recovered.',items:[warm,I('shadow',3,'2-minute round',60,{seconds:120}),I('bike',1,'25 minutes',0,{seconds:1500,progression:{4:{reps:'30 minutes',seconds:1800},6:{reps:'35 minutes',seconds:2100},8:{reps:'35 minutes',seconds:2100}}}),I('ropes',6,'20 seconds work',40,{seconds:20,conditioning:true,progression:{4:{sets:7},6:{sets:8},8:{sets:8}},notes:'RPE 7–8/10, with consistent waves through all intervals. Recover 40 seconds after each effort. This replaces separate sprint intervals.',techniqueDose:{sets:2,reps:'10 seconds · easy waves',seconds:10,rest:60,notes:'Coach load unknown or hard: technique only, RPE 4–5. Skip if shoulders are tired.'}}),cool]},
 {id:'wed',label:'Wednesday',title:'Power & strength B',minutes:'60–75 min',description:'A focused second strength session. Finish fresh enough for Thursday coaching.',items:[warm,power('jump','3 reps'),power('chestThrow','3 reps'),I('hinge',3,'6 reps',120),I('lunge',2,'6 each leg',90),I('pulldown',2,'8 reps',90),I('sidePlank',2,'20–30 seconds each side',45,{seconds:25}),I('shadow',2,'2-minute round',60,{seconds:120}),cool]},
 {id:'thu',label:'Thursday',title:'Boxing with your coach',minutes:'45–60 min',description:'Coaching is its own session. Follow your coach’s plan and share how you feel.',items:[I('coach',1,'45–60 minutes',0)]},
 {id:'fri',label:'Friday',title:'Recover & reset',minutes:'Rest',description:'Optional comfortable walking. No hard gym session scheduled.',items:[I('rest',1,'Rest or easy walk',0)]},
 {id:'sat',label:'Saturday',title:'Boxing with your coach',minutes:'45–60 min',description:'Technique, feedback and any coach-led conditioning or sparring.',items:[I('coach',1,'45–60 minutes',0)]},
 {id:'sun',label:'Sunday',title:'Rest day',minutes:'Rest',description:'Recover before the next lifting week.',items:[I('rest',1,'Rest',0)]}
];
return {equipment,exercises,days,
review:{summary:'Two power-and-strength sessions, an aerobic/skills day, two coached sessions and two recovery days. Your lifting weeks stay unchanged.',points:[
'Strength is a form of resistance training. This plan covers strength, explosive power, trunk control, aerobic capacity and conditioning without creating duplicate quotas.',
'Monday and Wednesday provide low-volume jumps/throws followed by controlled strength work. Leave approximately 3 clean repetitions in reserve; no training to failure.',
'Sled pushes use an intermediate resisted-work dose; battle ropes use a full interval block. Neither is guaranteed to increase punching power. Their load and rest determine the training effect.',
'Until coaching load is known, sled and rope blocks stay at easy technique doses. If coaching includes hard conditioning or sparring, retain that lighter mode and omit blocks when tired.',
'The new sled and rope work replaces additional hard interval finishers. Wednesday has no hard conditioning before Thursday coaching.',
'Gym fitness supports boxing; technique, partner work, sparring decisions and competition readiness belong with your coach. This is a foundation plan, not a tournament taper.',
'All boxing-week sessions are under 105 minutes including rests. Lifting sessions and Thursday/Saturday coaching can be separate.',
'Progress only at the next boxing-focused week and only when movement quality and recovery are good. Six to seven hours of sleep may limit recovery; create more sleep opportunity when possible.',
'Visuals are simplified movement sequences, not a form assessment. Use the linked coaching guides and ask a trainer to demonstrate unfamiliar equipment. Stop an exercise if it causes pain.'
]},
progression:[{week:1,title:'A · Your lifting routine',detail:'Keep your usual split and exercises. Thursday and Saturday coaching remain separate sessions as needed.'},{week:2,title:'B · Learn the movements',detail:'Use starting doses. Intermediate baseline: power 3 sets; sled 4 × 15 m with 120 s rest; ropes 6 × 20 s / 40 s rest. Tuesday cardio 25 min. Confirm coaching load before using full conditioning doses.'},{week:3,title:'A · Your lifting routine',detail:'Continue your unchanged lifting rotation and coaching.'},{week:4,title:'B · Add a little volume',detail:'If recovered, sled rises to 5 × 15 m and ropes to 7 × 20 s / 40 s. Power stays at 3 sets; Tuesday cardio 30 min. Hold any increase if coaching quality drops.'},{week:5,title:'A · Your lifting routine',detail:'Continue your unchanged lifting rotation and coaching.'},{week:6,title:'B · Consolidate capacity',detail:'Keep power at 3 sets. Sled: 5 × 20 m / 120 s rest; ropes: 8 × 20 s / 40 s rest. Tuesday cardio: 35 min. Add the smallest strength load only when 3 good repetitions remain; no automatic weight increase.'},{week:7,title:'A · Your lifting routine',detail:'Continue your unchanged lifting rotation and coaching.'},{week:8,title:'B · Review and repeat',detail:'Repeat week 6. If tired, use reduced volume. Compare easy-cardio effort and coaching feedback; do not test maximal punch power.'}],
sources:[{...sources.power,note:'Coaching methods for brief explosive work; direct transfer from individual exercises has limited evidence.'},{label:'Dunn et al. · strength and punch-force study',url:'https://pubmed.ncbi.nlm.nih.gov/32218063/',note:'Association in highly trained male boxers; not proof of this app’s exact program.'},{label:'NSCA · battle ropes for conditioning',url:'https://www.nsca.com/education/articles/ptq/utilizing-battling-rope-exercises-for-hiit-and-smit/',note:'Supports classifying ropes as conditioning rather than maximal strength.'},{...sources.sled,note:'Technique reference, not a boxing-specific trial.'},{...sources.shadow,note:'Purposeful shadowboxing themes to review with your coach.'},{label:'ACSM · 2026 resistance training guidance',url:'https://acsm.org/resistance-training-guidelines-update-2026/',note:'General strength/power programming principles, individualized to goals.'},{label:'Athlete sleep consensus',url:'https://bjsm.bmj.com/content/55/7/356',note:'Sleep needs vary with the athlete and training load.'}],
};
})();
