/* Spanish display catalog. Training IDs, doses and decision rules remain canonical. */
(() => {
  const entries = Object.create(null), D = window.BOXING_DATA;
  const add = (en, es) => { if (typeof en === 'string') entries[en] = es; };
  const pair = (en, es) => { if (Array.isArray(en)) en.forEach((v,i) => pair(v,es[i])); else if (en && typeof en === 'object') Object.keys(es).forEach(k => pair(en[k],es[k])); else add(en,es); };
  const exercise = (id, name, purpose, setup, steps, cues, avoid, substitutionNote) => pair(D.exercises.find(e => e.id === id), {name,purpose,setup,steps,cues,avoid,...(substitutionNote?{substitutionNote}:{})});
  pair(D.equipment.map(e=>e.name), ['Mancuernas','Banco de ejercicio estable','Balón medicinal ligero para lanzar','Pared autorizada para lanzar balones','Trineo de empuje','Carril despejado y autorizado para el trineo','Cuerdas de batalla con anclaje seguro','Bicicleta estática','Máquina de remo','Espacio despejado para caminar o trotar','Suelo de ejercicio despejado y antideslizante','Colchoneta o suelo acolchado','Estación de poleas','Máquina de jalón al pecho','Bandas de resistencia','Anclaje adecuado y seguro para bandas','Plataforma baja y estable']);
  exercise('warmup','Prepárate para moverte','Eleva la temperatura corporal y ensaya los movimientos de hoy.','Despeja un área pequeña. Empieza suavemente.', ['Marcha o camina a ritmo suave durante 3 minutos.','Mueve tobillos, caderas y hombros en rangos cómodos durante 2 minutos.','Ensaya sentadillas, bisagras de cadera y los lanzamientos de hoy sin carga; haz series de aproximación ligeras antes de levantar peso.'],['Aumenta el esfuerzo gradualmente.','Practica los aterrizajes antes de saltar.'],['No empieces con saltos máximos ni levantamientos pesados.']);
  exercise('jump','Salto vertical con pausa','Practica producir fuerza rápidamente con las piernas y aterrizar con control.','Pies aproximadamente al ancho de las caderas; despeja el espacio superior y de aterrizaje.', ['Ponte erguido y flexiona ligeramente caderas y rodillas.','Impúlsate hacia arriba con rapidez y coordinación, acompañando con los brazos.','Aterriza suavemente con ambos pies, flexiona las rodillas y vuelve a prepararte por completo.'],['Empieza con una altura de salto cómoda.','Descansa 90–120 segundos entre series.'],['Detente si empeora el aterrizaje o disminuye la altura.','Este bloque no incluye saltos con carga ni saltos desde una altura.'],'Si saltar resulta incómodo, omite este ejercicio de potencia; una sentadilla lenta no es un sustituto equivalente.');
  exercise('rotation','Lanzamiento rotacional con balón medicinal','Practica generar fuerza rápidamente con piernas y tronco.','Usa un balón ligero para lanzar, normalmente de 1–3 kg; colócate de lado a una pared autorizada y a una distancia segura.', ['Sujeta el balón con ambas manos junto a la parte exterior de la cadera; flexiona ligeramente las rodillas.','Gira los pies y las caderas junto con el tronco y lanza hacia la pared.','Deja que el balón se detenga de forma segura; vuelve a prepararte y repite por ambos lados.'],['Pide a un entrenador que te lo demuestre en la primera sesión.','Prioriza la velocidad frente a un balón pesado.'],['No gires únicamente desde la zona lumbar.','No atrapes un rebote rápido cerca de la cara.'],'Una flexión rápida inclinada trabaja la velocidad de empuje del tren superior; no reproduce el lanzamiento rotacional.');
  exercise('chestThrow','Pase de pecho con balón medicinal','Practica un empuje rápido con ambos brazos.','Usa un balón ligero para lanzar y una pared autorizada con espacio despejado para el rebote.', ['Adopta una postura equilibrada, rodillas suaves y balón frente al pecho.','Estabiliza el tronco e impulsa rápidamente el balón hacia delante con ambas manos.','Permite un rebote seguro, recoge el balón y vuelve a preparar la postura.'],['Mantén rápida cada repetición.','Pide una demostración para elegir el balón y preparar la pared.'],['No lo conviertas en un circuito continuo de fatiga.']);
  exercise('squat','Sentadilla goblet','Mantén la fuerza de piernas con un volumen de trabajo definido.','Sujeta una mancuerna cerca del pecho; coloca los pies a una anchura cómoda.', ['Ponte erguido, estabiliza suavemente el tronco y distribuye la presión en ambos pies.','Flexiona caderas y rodillas juntas hasta una profundidad cómoda.','Empuja el suelo y vuelve a ponerte de pie con control.'],['Deja aproximadamente 3 repeticiones buenas en reserva.','Puedes usar una variante de sentadilla que ya conozcas.'],['No busques más profundidad redondeando la espalda.']);
  exercise('press','Press de banca con mancuernas','Entrena la fuerza de empuje sin agotar los hombros.','Acuéstate en un banco estable, con los pies apoyados y las mancuernas bajo control.', ['Empieza con las mancuernas sobre el pecho y las muñecas alineadas.','Baja lentamente, con los codos en un ángulo cómodo respecto al tronco.','Empuja hacia arriba con fluidez y repite sin rebotar.'],['Termina con 3 repeticiones en reserva.','Mantén estables los pies y la parte superior de la espalda.'],['Evita una profundidad dolorosa o codos abiertos sin control.']);
  exercise('row','Remo a una mano con apoyo','Equilibra los empujes con un trabajo de tracción controlado para la espalda alta.','Apoya una mano y una rodilla en un banco estable; sujeta una mancuerna con la otra mano.', ['Deja colgar el brazo que trabaja y mantén estable el tronco.','Lleva el codo hacia la cadera sin girar el tronco.','Baja lentamente hasta el inicio; completa ambos lados.'],['Mantén una posición neutra y cómoda de la columna.','Deja 3 repeticiones en reserva.'],['No tires de la mancuerna con un impulso brusco.'],'¿No tienes bandas ni mancuernas disponibles? Deja este espacio sin completar hoy. Un empuje con peso corporal no sustituye una tracción comparable.');
  exercise('pallof','Press Pallof','Resiste la rotación no deseada del tronco mientras mueves los brazos.','Coloca una polea aproximadamente a la altura del pecho; ponte de lado y elige una carga manejable.', ['Sujeta el agarre frente al pecho con ambas manos.','Extiende los brazos hacia delante y pausa 1–2 segundos sin girar.','Vuelve lentamente; repite mirando hacia el otro lado.'],['Respira con normalidad.','Mantén las costillas alineadas sobre la pelvis.'],['No uses una carga que te haga girar la postura.']);
  exercise('hinge','Peso muerto rumano con mancuernas','Entrena la fuerza de la bisagra de cadera con isquiotibiales y glúteos.','Ponte de pie con las mancuernas cerca de los muslos y las rodillas ligeramente flexionadas.', ['Estabiliza el tronco y mantén las pesas cerca de las piernas.','Lleva las caderas hacia atrás con la columna neutra hasta sentir un estiramiento cómodo de los isquiotibiales.','Empuja con los pies y lleva las caderas hacia delante hasta quedar erguido.'],['La profundidad depende de tu movilidad.','Deja 3 repeticiones en reserva.'],['No redondees la espalda ni te inclines hacia atrás al terminar.']);
  exercise('lunge','Zancada hacia atrás','Entrena la fuerza y el equilibrio de cada pierna por separado.','Usa mancuernas ligeras o tu peso corporal; deja espacio para dar un paso atrás.', ['Ponte de pie con equilibrio y los pies al ancho de las caderas.','Da un paso atrás con un pie y baja con control, manteniendo plano el pie delantero.','Empuja con la pierna delantera para volver; repite por ambos lados.'],['Empieza ligero antes del entrenamiento del jueves.','Usa una longitud de paso cómoda.'],['No golpees el suelo con la rodilla trasera.']);
  exercise('pulldown','Jalón al pecho','Entrena la fuerza de tracción vertical del tren superior.','Ajusta bien el apoyo de muslos y elige una carga manejable.', ['Siéntate erguido y agarra la barra algo más abierta que los hombros.','Lleva los codos hacia abajo mientras la barra se acerca a la parte alta del pecho.','Vuelve lentamente por encima de la cabeza sin despegarte del asiento.'],['Mantén el cuello relajado.','Deja 3 repeticiones buenas en reserva.'],['No tires detrás de la cabeza ni te balancees hacia atrás.'],'Un remo aporta trabajo de tracción, pero cambia la dirección de la carga. Sin equipo adecuado para tirar, omite este espacio.');
  exercise('sidePlank','Plancha lateral','Entrena la estabilidad lateral del tronco.','Acuéstate de lado con el codo debajo del hombro. Flexiona las rodillas para la versión más fácil.', ['Alinea el hombro sobre el codo y estabiliza suavemente el tronco.','Eleva las caderas para que el cuerpo apoyado forme una línea recta.','Mantén la posición respirando, baja lentamente y cambia de lado.'],['Detente antes de perder la posición.','Si hace falta, empieza con las rodillas flexionadas.'],['No mantengas la posición si duele el hombro.']);
  exercise('sled','Empuje de trineo','Añade impulso de piernas con resistencia y capacidad de trabajo controlados. No es una prueba directa de potencia de golpeo.','Usa agarres altos y un carril autorizado y despejado de 15–20 metros. La fricción del suelo cambia mucho la carga.', ['Sujeta los agarres con firmeza, estabiliza el tronco e inclina el cuerpo como una unidad.','Da pasos cortos y potentes, empujando con fluidez durante los 15–20 metros indicados.','Detente con control y recupérate por completo antes del siguiente recorrido.'],['Dosis normal: esfuerzo percibido (RPE) 7/10, sin forzar repeticiones lentas.','Aprende primero el movimiento con una carga fácil.'],['No improvises empujando una cinta de correr apagada.','Este bloque de base no incluye esprints máximos con trineo.'],'Las subidas a plataforma y las sentadillas divididas aportan resistencia de piernas controlada; no reproducen la fuerza horizontal ni la demanda exacta del trineo.');
  exercise('ropes','Ondas alternas con cuerdas de batalla','Entrena esfuerzos repetidos del tren superior; es acondicionamiento, no fuerza máxima.','Revisa el anclaje; sujeta un extremo de cuerda en cada mano, con holgura y una postura cómoda.', ['Flexiona suavemente las rodillas, inclina ligeramente la cadera y relaja los hombros.','Mueve los brazos arriba y abajo de forma alterna para enviar ondas pequeñas hacia el anclaje.','Detente al terminar el intervalo de trabajo y recupérate respirando suavemente.'],['Controla las costillas y mantén constantes las ondas.','Dosis normal: esfuerzo 7–8/10, nunca al máximo.'],['Detente si elevas los hombros, arqueas la zona lumbar o pierdes la técnica.'],'La bicicleta o la marcha conservan el espacio de acondicionamiento por intervalos, pero pierden el énfasis de las cuerdas en el tren superior.');
  exercise('bike','Bicicleta estática suave','Desarrolla la capacidad aeróbica sostenida sin un bloque intenso al final.','Ajusta el sillín para que la rodilla quede ligeramente flexionada en la parte baja de la pedalada.', ['Empieza a pedalear con una resistencia cómoda.','Encuentra un esfuerzo que te permita hablar en frases completas con facilidad.','Mantén un ritmo estable y baja la intensidad en los últimos minutos.'],['Usa la prueba del habla: aproximadamente un esfuerzo de 3–4/10.','El cardio no es una carrera.'],['Si la respiración impide conversar, reduce la resistencia.']);
  exercise('walk','Caminata o trote suave','Desarrolla la capacidad de trabajo aeróbico sostenido.','Elige una ruta despejada y predecible o una cinta de correr encendida normalmente.', ['Empieza caminando con comodidad.','Aumenta el ritmo solo mientras puedas hablar en frases completas.','Mantén un ritmo suave y reduce la velocidad para terminar.'],['Trota solo si ya te resulta cómodo.'],['No añadas esprints a este espacio suave.']);
  exercise('shadow','Boxeo de sombra con objetivo','Ensaya el juego de pies, el equilibrio y las combinaciones que enseña tu entrenador.','Usa las manos vacías y un suelo despejado. Imagina un rival a una distancia realista.', ['Asalto 1: postura y pasos cortos hacia delante, atrás y a los lados.','Asalto 2: el jab de tu entrenador, vuelta a la guardia y salida.','Asalto 3: una combinación conocida seguida de una defensa que te haya enseñado tu entrenador.'],['Muévete con soltura; vuelve a empezar si pierdes el equilibrio.','Descansa 1 minuto entre asaltos.'],['No añadas mancuernas ni inventes defensas desconocidas.']);
  exercise('cooldown','Vuelta a la calma suave','Deja que se normalice la respiración y valora cómo te fue en la sesión.','Adopta una postura cómoda, de pie o sentado.', ['Baja el ritmo gradualmente durante 2 minutos.','Muévete o estira suavemente dentro de un rango cómodo.','Registra la fatiga y los movimientos que necesiten comentarios de tu entrenador.'],['La respiración normal debe volver gradualmente.'],['No fuerces los estiramientos.']);
  exercise('coach','Sesión de boxeo con entrenador','Practica técnica y recibe comentarios de tu entrenador.','Lleva el equipo que pida tu entrenador; las sustituciones de material de gimnasio no se aplican.', ['Cuenta a tu entrenador cómo han sido tus entrenamientos recientes y tu fatiga.','Sigue la sesión que indique, incluido cualquier trabajo con compañero supervisado.','Pide una corrección para ensayarla en la siguiente práctica individual.'],['Jueves y sábado: 45–60 minutos.','El entrenador decide sobre el sparring y la preparación para competir.'],['No añadas sparring sin supervisión como sustituto.']);
  exercise('rest','Día de recuperación','Recupérate para la siguiente sesión útil.','Hoy no hay entrenamiento que completar.', ['Da un paseo cómodo si quieres moverte.','Come con normalidad, hidrátate y reserva tiempo para dormir.','Comprueba que hayan mejorado las agujetas o la fatiga antes de la siguiente sesión.'],['Busca sentirte recuperado, no acumular volumen extra.'],[]);
  exercise('pushup','Flexión controlada','Sustituye el press de banca con un empuje que puedes adaptar a tu nivel.','Usa una pared o un banco estable para inclinarte si las flexiones en el suelo son demasiado exigentes.', ['Coloca las manos algo más abiertas que los hombros y alinea el cuerpo.','Baja el pecho con los codos en un ángulo cómodo.','Empuja para subir y mantén estable el tronco.'],['Elige una inclinación que deje 3 repeticiones en reserva.'],['Evita hundir las caderas o trabajar con dolor de muñecas.']);
  exercise('fastPushup','Flexión rápida inclinada','Una alternativa sencilla de empuje rápido cuando no puedes lanzar.','Usa un banco estable asegurado contra el movimiento. Elige una inclinación fácil.', ['Alinea el cuerpo y baja con control.','Empuja rápidamente manteniendo las manos en contacto con el banco.','Vuelve a prepararte por completo antes de la siguiente repetición.'],['Mantén ágiles todas las repeticiones.','No hace falta dar palmadas ni despegar las manos.'],['El banco no debe deslizarse ni volcarse.'],'Si no hay un banco seguro, omite este espacio de potencia en lugar de improvisar un apoyo inestable.');
  exercise('splitSquat','Sentadilla dividida con peso corporal','Ofrece una opción controlada de fuerza de piernas sin equipo.','Adopta una postura dividida; apóyate suavemente en una pared si necesitas equilibrio.', ['Colócate con un pie delante del otro de forma cómoda, ambos mirando hacia delante.','Baja verticalmente con control y mantén plano el pie delantero.','Empuja con la pierna delantera para subir; repite por ambos lados.'],['Si resulta fácil, baja lentamente durante 3 segundos.'],['Mantén cómodo el movimiento de rodillas; evita rebotar.']);
  exercise('bandRow','Remo de pie con banda','Ofrece tracción horizontal cuando no hay máquinas ni mancuernas.','Revisa la banda y fíjala a un anclaje adecuado a la altura del pecho.', ['Sujeta la banda con los brazos hacia delante y una postura equilibrada.','Lleva los codos hacia atrás junto a las costillas, sin inclinarte.','Vuelve lentamente con control.'],['Usa una tensión que permita 8–12 repeticiones limpias.'],['No la fijes a muebles sueltos ni a una puerta sin asegurar.']);
  exercise('bandPallof','Press Pallof con banda','Resiste la rotación del tronco con una banda.','Revisa y ancla la banda a la altura del pecho. Ponte de lado.', ['Sujeta la banda cerca del pecho.','Extiende los brazos sin permitir que gire el tronco.','Vuelve lentamente y repite por ambos lados.'],['Empieza con una tensión ligera.'],['No uses un anclaje inseguro.']);
  exercise('deadbug','Bicho muerto (dead bug)','Control del tronco con poco equipo mediante movimientos lentos de brazos y piernas.','Acuéstate boca arriba, con brazos elevados y rodillas flexionadas sobre las caderas.', ['Estabiliza suavemente el tronco y mantén la espalda en una posición cómoda y estable.','Extiende el brazo y la pierna opuestos solo hasta donde puedas controlar.','Vuelve y alterna lados lentamente.'],['Exhala al extender las extremidades.'],['No arquees la espalda para llegar más lejos.']);
  exercise('bridge','Puente de glúteos','Una alternativa de extensión de cadera con poca carga cuando faltan pesas.','Acuéstate boca arriba con las rodillas flexionadas y los pies planos.', ['Estabiliza suavemente el tronco con los pies al ancho de las caderas.','Empuja con los pies y eleva las caderas hasta alinear tronco y muslos.','Baja lentamente y repite sin arquear la espalda.'],['Pausa brevemente arriba.'],['No fuerces la extensión de la zona lumbar.']);
  exercise('stepup','Subida a plataforma baja','Trabajo de piernas controlado cuando no hay trineo.','Usa una plataforma baja y estable y espacio para bajar de forma segura.', ['Coloca un pie completo sobre la plataforma.','Empuja con esa pierna para subir a la plataforma sin rebotar.','Baja lentamente; completa ambos lados.'],['Empieza con tu peso corporal.'],['No uses una silla ni una caja inestable.']);
  exercise('bikeIntervals','Intervalos en bicicleta','Sustituto de acondicionamiento por intervalos cuando no hay cuerdas de batalla.','Ajusta el sillín y la resistencia para pedalear con fluidez.', ['Pedalea suavemente antes del primer intervalo.','Aumenta la resistencia o la cadencia durante el tiempo de trabajo indicado.','Pedalea suavemente durante la recuperación.'],['Mantén repetibles los esfuerzos intensos, aproximadamente a 7/10.'],['No hagas esprints al máximo ni arranques de pie.']);
  exercise('marchIntervals','Intervalos de marcha rápida','Alternativa de acondicionamiento de bajo impacto sin equipo.','Elige un espacio despejado o usa un apoyo estable si lo requiere tu equilibrio.', ['Empieza marchando cómodamente.','Aumenta el movimiento de brazos y el ritmo durante el intervalo de trabajo.','Vuelve a una marcha suave durante la recuperación.'],['Ajusta el ritmo según la respiración.'],['Puede resultar menos exigente que las cuerdas; no añadas impacto solo para igualar la fatiga.'],'Alternativa de bajo impacto; no equivale al estímulo de acondicionamiento del tren superior.');
  exercise('easyMarch','Marcha suave','Una opción de movimiento suave sin equipo.','Busca un lugar despejado para estar de pie; mantén un esfuerzo cómodo.', ['Empieza con pasos cortos de marcha suave.','Mantén un esfuerzo que permita conversar y mueve los brazos con soltura.','Baja el ritmo gradualmente para terminar.'],['Si el espacio y el equipo lo permiten, la bicicleta o caminar pueden facilitar el trabajo aeróbico sostenido.'],[],'Una alternativa menos exigente; el estímulo aeróbico depende de la respiración y del ritmo.');
  pair(D.days.map(d=>[d.label,d.title,d.description]), [
    ['Lunes','Potencia y fuerza A','Primero el trabajo explosivo, después la fuerza. Termina con práctica de trineo y cardio suave.'],
    ['Martes','Técnica y acondicionamiento','Boxeo de sombra con objetivo, base aeróbica sostenida y un bloque completo de cuerdas de nivel intermedio cuando estés recuperado.'],
    ['Miércoles','Potencia y fuerza B','Una segunda sesión de fuerza bien enfocada. Termina con energía suficiente para el entrenamiento del jueves.'],
    ['Jueves','Boxeo con tu entrenador','La sesión con entrenador es independiente. Sigue su plan y cuenta cómo te sientes.'],
    ['Viernes','Recupera y reinicia','Caminata cómoda opcional. No hay sesión intensa de gimnasio programada.'],
    ['Sábado','Boxeo con tu entrenador','Técnica, comentarios y cualquier acondicionamiento o sparring dirigido por el entrenador.'],
    ['Domingo','Día de descanso','Recupérate antes de la siguiente semana de pesas.']
  ]);
  pair(D.review, {summary:'Dos sesiones de potencia y fuerza, un día de trabajo aeróbico y técnica, dos sesiones con entrenador y dos días de recuperación. Tus semanas de pesas se mantienen sin cambios.',points:[
    'La fuerza es una forma de entrenamiento de resistencia. Este plan incluye fuerza, potencia explosiva, control del tronco, capacidad aeróbica y acondicionamiento sin crear cuotas duplicadas.',
    'Lunes y miércoles incluyen pocos saltos y lanzamientos, seguidos de fuerza controlada. Deja aproximadamente 3 repeticiones limpias en reserva; no entrenes al fallo.',
    'Los empujes de trineo usan una dosis intermedia de trabajo con resistencia; las cuerdas de batalla tienen un bloque completo de intervalos. Ninguno garantiza aumentar la potencia de golpeo. La carga y el descanso determinan su efecto.',
    'Hasta conocer la carga del entrenamiento de boxeo, los bloques de trineo y cuerdas se mantienen como práctica técnica suave. Si el boxeo incluye acondicionamiento intenso o sparring, conserva ese modo ligero y omite los bloques cuando estés cansado.',
    'El trabajo nuevo de trineo y cuerdas sustituye los bloques intensos adicionales de intervalos al final. El miércoles no hay acondicionamiento intenso antes del entrenamiento del jueves.',
    'La forma física apoya al boxeo; la técnica, el trabajo con compañero, las decisiones sobre sparring y la preparación para competir corresponden a tu entrenador. Es un plan de base, no una puesta a punto para un torneo.',
    'Todas las sesiones de la semana de boxeo duran menos de 105 minutos, incluidos los descansos. Las sesiones de pesas y el boxeo de jueves y sábado pueden ser independientes.',
    'Progresa solo en la siguiente semana centrada en boxeo y cuando la técnica y la recuperación sean buenas. Dormir de seis a siete horas puede limitar la recuperación; busca más tiempo para dormir cuando puedas.',
    'Las imágenes son secuencias simplificadas, no una evaluación de tu técnica. Usa las guías enlazadas y pide a un entrenador que demuestre el equipo desconocido. Detén un ejercicio si causa dolor.'
  ]});
  pair(D.progression.map(p=>[p.title,p.detail]), [
    ['A · Tu rutina de pesas','Conserva tu división y tus ejercicios habituales. El boxeo de jueves y sábado sigue como sesiones separadas cuando haga falta.'],
    ['B · Aprende los movimientos','Usa las dosis iniciales. Base intermedia: potencia, 3 series; trineo, 4 × 15 m con 120 s de descanso; cuerdas, 6 × 20 s / 40 s de descanso. Cardio del martes: 25 min. Confirma la carga del boxeo antes de usar las dosis completas de acondicionamiento.'],
    ['A · Tu rutina de pesas','Continúa tu rotación de pesas y el boxeo sin cambios.'],
    ['B · Añade algo de volumen','Si estás recuperado, el trineo sube a 5 × 15 m y las cuerdas a 7 × 20 s / 40 s. La potencia sigue en 3 series; cardio del martes: 30 min. No aumentes si baja la calidad del boxeo.'],
    ['A · Tu rutina de pesas','Continúa tu rotación de pesas y el boxeo sin cambios.'],
    ['B · Consolida la capacidad','Mantén la potencia en 3 series. Trineo: 5 × 20 m / 120 s de descanso; cuerdas: 8 × 20 s / 40 s de descanso. Cardio del martes: 35 min. Añade el mínimo peso solo si quedan 3 repeticiones buenas en reserva; no hay aumentos automáticos de carga.'],
    ['A · Tu rutina de pesas','Continúa tu rotación de pesas y el boxeo sin cambios.'],
    ['B · Revisa y repite','Repite la semana 6. Si estás cansado, reduce el volumen. Compara el esfuerzo del cardio suave y los comentarios del entrenador; no pruebes la potencia máxima de golpeo.']
  ]);
  pair(D.sources.map(s=>s.note), ['Métodos de entrenamiento para trabajo explosivo breve; la evidencia de transferencia directa de ejercicios individuales es limitada.','Asociación en boxeadores varones de alto nivel; no demuestra el efecto del programa exacto de esta app.','Apoya clasificar las cuerdas como acondicionamiento y no como fuerza máxima.','Referencia de técnica, no un ensayo específico de boxeo.','Temas de boxeo de sombra con objetivo para revisar con tu entrenador.','Principios generales de programación de fuerza y potencia adaptados a los objetivos.','Las necesidades de sueño varían según el deportista y la carga de entrenamiento.']);
  window.ROUNDWORK_ES = entries;
  window.ROUNDWORK_ADD_ES = pairs => pairs.forEach(([en,es])=>add(en,es));
})();
