(() => {
  const button=document.createElement('button');button.className='button button-ghost button-small';button.textContent='On your phone ↗';button.id='phone-help';
  document.querySelector('.site-header').insertBefore(button,document.querySelector('#help-button'));
  const dialog=document.createElement('dialog');dialog.className='phone-dialog';dialog.setAttribute('aria-labelledby','phone-title');
  dialog.innerHTML='<header class="modal-header"><div><div class="eyebrow">ANDROID + IPHONE</div><h2 id="phone-title">Your gym, in your pocket.</h2></div><button class="icon-button" id="phone-close" aria-label="Close phone help">×</button></header><div class="modal-content"><p>Open this same website on either phone. No account is required; your settings and logs stay on your device.</p><section class="guide-section"><h3>iPhone</h3><p>Open in Safari → Share → Add to Home Screen. Keep “Open as Web App” on if shown, then Add.</p><h3>Android</h3><p>Open in Chrome → menu (⋮) → Add to home screen or Install app.</p><p><a href="https://support.apple.com/en-lamr/guide/iphone/iphea86e5236/ios" target="_blank" rel="noopener">Apple instructions ↗</a> · <a href="https://support.google.com/chrome/answer/9658361?co=GENIE.Platform%3DAndroid&hl=en" target="_blank" rel="noopener">Android instructions ↗</a></p></section><section class="guide-section"><h3>When gym reception is weak</h3><p id="offline-status">Connect once to save the written steps and movement backups. Videos and external expert pages need internet. Offline availability depends on your browser retaining the app’s saved files.</p><p>Timers catch up when you return to the screen; phone lock screens can suspend alerts. Keep the app visible during timed work.</p></section><section class="guide-section"><h3>Take your progress to the other phone</h3><p>Equipment and logs are saved in this browser. They do not automatically sync between phones. Export a backup, transfer that file yourself, and import it on the other phone.</p><div class="phone-actions"><button class="button button-dark" id="backup-export">Export backup</button><button class="button button-ghost" id="backup-import">Import backup</button></div><input id="backup-file" type="file" accept="application/json,.json" hidden><p id="backup-status" role="status"></p><button id="backup-confirm" class="button button-primary" hidden>Replace this device’s data</button></section></div>';
  document.body.appendChild(dialog);button.onclick=()=>dialog.showModal();document.querySelector('#phone-close').onclick=()=>dialog.close();
  dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
  let pending=null;
  const status=document.querySelector('#backup-status');
  document.querySelector('#backup-export').onclick=()=>{try{const state=JSON.parse(localStorage.getItem('roundwork.v1')||'{}');const blob=new Blob([JSON.stringify({app:'roundwork',version:1,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='roundwork-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Backup downloaded. It includes your equipment notes and logs; share it only where you intend.';}catch{status.textContent='This browser could not export stored data.'}};
  document.querySelector('#backup-import').onclick=()=>document.querySelector('#backup-file').click();
  document.querySelector('#backup-file').onchange=async e=>{pending=null;document.querySelector('#backup-confirm').hidden=true;const file=e.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error('File too large.');const b=JSON.parse(await file.text());if(b.app!=='roundwork'||b.version!==1||!b.state||typeof b.state!=='object')throw Error('Not a Roundwork backup.');const x=b.state;const clean={week:Number.isInteger(x.week)&&x.week>=1&&x.week<=8?x.week:2,day:window.BOXING_DATA.days.some(d=>d.id===x.day)?x.day:'mon',equipment:{},coachLoad:['unknown','technical','hard'].includes(x.coachLoad)?x.coachLoad:'unknown',readiness:['normal','tired'].includes(x.readiness)?x.readiness:'normal',notes:typeof x.notes==='string'?x.notes.slice(0,12000):'',logs:{},sessions:{},swaps:{},sessionSettings:window.RoundworkPlanner.cleanSettings(x.sessionSettings)};
  window.BOXING_DATA.equipment.forEach(eq=>{if(['yes','no','unknown'].includes(x.equipment?.[eq.id]))clean.equipment[eq.id]=x.equipment[eq.id]});
  const ids=new Set(window.BOXING_DATA.exercises.map(e=>e.id));
  for(const key of ['logs','sessions','swaps'])if(x[key]&&typeof x[key]==='object'&&!Array.isArray(x[key]))for(const [k,v] of Object.entries(x[key])){if(!/^[1-8]:(mon|tue|wed|thu|fri|sat|sun)(:[a-zA-Z]+)?$/.test(k))continue;if(key==='swaps'){if(ids.has(v))clean[key][k]=v;}else if(v&&typeof v==='object')clean[key][k]=JSON.parse(JSON.stringify(v));}
  pending=clean;status.textContent='Backup ready. Importing replaces equipment, notes and logs currently saved on this device.';document.querySelector('#backup-confirm').hidden=false;}catch(err){status.textContent=err.message||'Could not read this backup.'}e.target.value='';};
  document.querySelector('#backup-confirm').onclick=()=>{if(!pending)return;try{localStorage.setItem('roundwork.v1',JSON.stringify(pending));location.reload();}catch{status.textContent='Storage unavailable; import was not saved.'}};
  if('serviceWorker' in navigator && location.protocol!=='file:')navigator.serviceWorker.register('./sw.js?v=1.3.1').then(()=>navigator.serviceWorker.ready).then(()=>{document.querySelector('#offline-status').textContent='The written steps and movement backups have been saved for offline use on this browser. Open the app once online on each phone. Videos and external expert pages need internet; browsers may clear saved files.'}).catch(()=>{document.querySelector('#offline-status').textContent='Offline saving is unavailable in this browser. The app works while online; videos and expert pages also need internet.'});
})();

