/* Authored bilingual planning explanations and consulted primary sources. */
(() => {
  const pairs=[
    ['SOURCE REVIEW · 8 OCTOBER 2026','REVISIÓN DE FUENTES · 8 DE OCTUBRE DE 2026'],
    ['Today’s exercise list reflects your level, time, equipment and recovery.','La lista de ejercicios de hoy refleja tu nivel, tiempo, equipo y recuperación.'],
    ['Use the rest shown on your current session card.','Usa el descanso indicado en la tarjeta de tu sesión actual.'],
    ['Rookie','Principiante'],['Intermediate','Intermedio'],['Advanced','Avanzado'],
    ['Choose this day’s session','Elige la sesión de este día'],['Saved for this week and day','Guardado para esta semana y día'],
    ['Exercise level','Nivel de ejercicios'],['Time available','Tiempo disponible'],['Estimated training:','Entrenamiento estimado:'],['within','dentro de'],['available','disponibles'],
    ['YOUR GYM COMPANION / ADAPTABLE 8-WEEK BLOCK','TU GUÍA DE GIMNASIO / BLOQUE ADAPTABLE DE 8 SEMANAS'],
    ['Choose by your experience with boxing-support exercises, not only your lifting strength. Rookie learns the basics; Intermediate knows the movements; Advanced has consistent training and coach-reviewed technique.','Elige según tu experiencia con ejercicios de apoyo al boxeo, no solo tu fuerza con pesas. Principiante aprende las bases; Intermedio conoce los movimientos; Avanzado entrena con constancia y tiene la técnica revisada por un entrenador.'],
    ['I am recovered and ready for this boxing week’s progression.','Estoy recuperado y listo para la progresión de esta semana de boxeo.'],
    ['Includes warm-up, cooldown, work, rests, equipment setup and transitions. Time for gym queues or learning a movement varies.','Incluye calentamiento, vuelta a la calma, trabajo, descansos, preparación del equipo y transiciones. El tiempo de espera o para aprender un movimiento varía.'],
    ['Your lifting routine stays unchanged. Level and time adaptation apply to the boxing-focused gym days.','Tu rutina de pesas sigue sin cambios. La adaptación de nivel y tiempo se aplica a los días de gimnasio enfocados en boxeo.'],
    ['How this session adapts','Cómo se adapta esta sesión'],['Planning evidence & limits','Evidencia y límites de la planificación'],
    ['Resistance work includes weights, bodyweight, bands and cables when available. Power, aerobic work and conditioning are balanced across the week; a short session does not have to contain every category.','El trabajo de resistencia incluye pesas, peso corporal, bandas y poleas cuando están disponibles. La potencia, el trabajo aeróbico y el acondicionamiento se equilibran durante la semana; una sesión corta no tiene que incluir todas las categorías.'],
    ['Changing choices does not erase completed work. Do not repeat exercises already completed today.','Cambiar las opciones no borra el trabajo completado. No repitas los ejercicios que ya completaste hoy.'],
    ['Completed with an earlier prescription. Do not repeat this slot today.','Completado con una dosis anterior. No repitas este bloque hoy.'],
    ['Rookie uses easy equipment practice.','Principiante usa práctica suave del equipo.'],
    ['Reduced strength and power work, shorter easy cardio, and no hard conditioning. Stop if movement quality falls.','Trabajo de fuerza y potencia reducido, cardio suave más corto y sin acondicionamiento intenso. Detente si baja la calidad del movimiento.'],
    ['Session updated. Keep the prescribed rests; completed work remains recorded.','Sesión actualizada. Mantén los descansos indicados; el trabajo completado sigue registrado.'],
    ['Follow the adapted dose below. Keep the prescribed rests and finish with your cooldown when your available time is up.','Sigue la dosis adaptada que se muestra abajo. Mantén los descansos indicados y termina con la vuelta a la calma cuando se agote tu tiempo disponible.'],
    ['Select 30–120 minutes for a boxing-focused gym day. The planner fits work and recovery inside that budget; lifting stays unchanged and coaching remains coach-led.','Selecciona 30–120 minutos para un día de gimnasio enfocado en boxeo. El plan ajusta trabajo y recuperación a ese tiempo; las pesas siguen sin cambios y el boxeo sigue dirigido por el entrenador.'],
    ['Level and time adaptation','Adaptación de nivel y tiempo'],
    ['Rookie uses simpler resistance movements and easy conditioning practice. Intermediate uses familiar power and strength work. Advanced adds controlled volume and longer rests, without maximal lifts or all-out finishers. Short sessions remove optional work; longer sessions mainly extend easy cardio, and may finish well before the selected time.','Principiante usa movimientos de resistencia más sencillos y práctica suave de acondicionamiento. Intermedio usa ejercicios conocidos de potencia y fuerza. Avanzado añade volumen controlado y descansos más largos, sin cargas máximas ni finales al límite. Las sesiones cortas omiten trabajo opcional; las largas amplían principalmente el cardio suave y pueden terminar antes del tiempo seleccionado.'],
    ['The estimate includes work, every displayed rest, warm-up, cooldown and setup time. Time saved is not converted into harder intervals. Technique, recovery and coaching load override the level choice. Select progression only after the previous boxing block was well tolerated.','La estimación incluye trabajo, cada descanso mostrado, calentamiento, vuelta a la calma y preparación. El tiempo ahorrado no se convierte en intervalos más intensos. La técnica, la recuperación y la carga del boxeo tienen prioridad sobre el nivel elegido. Selecciona la progresión solo si toleraste bien el bloque anterior de boxeo.'],
    ['Level-based repetitions in reserve, recovery days, equipment substitutions and the 30–120-minute time menu are practical programming choices. The adaptation rules are not a tested boxing intervention or a guarantee of safety. Lifting stays unchanged; a qualified coach should review workload and unfamiliar equipment.','Las repeticiones en reserva según nivel, los días de recuperación, las sustituciones de equipo y el menú de 30–120 minutos son decisiones prácticas de programación. Las reglas de adaptación no son una intervención de boxeo probada ni una garantía de seguridad. Las pesas siguen sin cambios; un entrenador cualificado debe revisar la carga y el equipo desconocido.'],
    ['Coaching is scheduled for 45–60 minutes. Arrange a shorter session with your coach; the app does not shorten sparring or coaching.','El boxeo con entrenador dura 45–60 minutos. Acuerda una sesión más corta con tu entrenador; la app no acorta el combate de práctica ni la clase.'],
    ['Follow your coach’s session. Extra available time does not add sparring or hard conditioning.','Sigue la sesión de tu entrenador. El tiempo adicional disponible no añade combate de práctica ni acondicionamiento intenso.'],
    ['Keep this a recovery day. An optional comfortable 10–20-minute walk is enough; the time selector does not create a hard workout.','Mantén este día para recuperarte. Un paseo cómodo opcional de 10–20 minutos es suficiente; el selector de tiempo no crea un entrenamiento intenso.'],
    ['Rookie: learn stable bodyweight movements and relaxed coach-taught shadowboxing. No jumps, throws or hard rope/sled intervals.','Principiante: aprende movimientos estables con peso corporal y boxeo de sombra relajado enseñado por tu entrenador. Sin saltos, lanzamientos ni intervalos intensos con cuerdas o trineo.'],
    ['Advanced: familiar movements, controlled strength effort, and fully rested power sets. No maximal lifts, depth jumps or all-out intervals.','Avanzado: movimientos conocidos, esfuerzo de fuerza controlado y series de potencia con descanso completo. Sin cargas máximas, saltos desde altura ni intervalos al límite.'],
    ['Intermediate: familiar jumps and throws, controlled strength sets, and repeatable conditioning when recovered.','Intermedio: saltos y lanzamientos conocidos, series de fuerza controladas y acondicionamiento repetible cuando estás recuperado.'],
    ['Time is a ceiling, not a target. Shorter sessions reduce volume; rest and warm-up are preserved. Stop when technique or speed falls.','El tiempo es un límite, no una meta. Las sesiones cortas reducen el volumen; se conservan los descansos y el calentamiento. Detente si baja la técnica o la velocidad.'],
    ['Starting-week volume is held until you confirm good recovery and movement quality for progression.','Se mantiene el volumen inicial hasta que confirmes buena recuperación y calidad de movimiento para progresar.'],
    ['Reset each repetition. Rest 180 seconds after each set; stop if speed or landing quality declines.','Reinicia cada repetición. Descansa 180 segundos después de cada serie; detente si baja la velocidad o la calidad del aterrizaje.'],
    ['Use an easy, controlled load or bodyweight. Leave at least 4 good repetitions in reserve.','Usa una carga suave y controlada o peso corporal. Deja al menos 4 repeticiones buenas en reserva.'],
    ['Use a familiar load; leave 2–3 good repetitions in reserve. No grinding or automatic weight increase.','Usa una carga conocida; deja 2–3 repeticiones buenas en reserva. Sin repeticiones forzadas ni aumentos automáticos de peso.'],
    ['Use a familiar load; leave 3 good repetitions in reserve. No grinding or automatic weight increase.','Usa una carga conocida; deja 3 repeticiones buenas en reserva. Sin repeticiones forzadas ni aumentos automáticos de peso.'],
    ['Move slowly and breathe normally. Stop before position deteriorates.','Muévete despacio y respira normalmente. Detente antes de perder la postura.'],
    ['Relaxed coach-taught footwork and combinations. Keep balance; this is technique practice, not a maximal punching circuit.','Desplazamientos y combinaciones relajados enseñados por tu entrenador. Mantén el equilibrio; es práctica de técnica, no un circuito de golpes máximos.'],
    ['Conversational pace, about 3–5/10 effort. Slow down if you cannot speak comfortably.','Ritmo que permite conversar, esfuerzo aproximado de 3–5/10. Baja el ritmo si no puedes hablar cómodamente.'],
    ['Easy familiarisation only, about 4/10 effort. Skip if fatigued.','Solo familiarización suave, esfuerzo aproximado de 4/10. Omite si estás fatigado.'],
    ['Repeatable 7/10 effort. No grinding or sprints; friction changes load.','Esfuerzo repetible de 7/10. Sin empujes forzados ni esprints; la fricción cambia la carga.'],
    ['Repeatable 7–8/10 effort, 60 seconds easy recovery. Never all-out.','Esfuerzo repetible de 7–8/10, 60 segundos de recuperación suave. Nunca al límite.'],
    ['Repeatable 7/10 effort, 40 seconds easy recovery. Never all-out.','Esfuerzo repetible de 7/10, 40 segundos de recuperación suave. Nunca al límite.'],
    ['Skip this conditioning slot when tired. Recover for coached boxing.','Omite este bloque de acondicionamiento si estás cansado. Recupérate para el boxeo con entrenador.'],
    ['Relaxed coach-taught stance and footwork; keep balance.','Postura y desplazamientos relajados enseñados por tu entrenador; mantén el equilibrio.'],
    ['Some optional exercises or sets were removed to fit your time. Do not add them back as a finisher.','Se omitieron algunos ejercicios o series opcionales para ajustarse a tu tiempo. No los añadas como bloque final.'],
    ['Estimates include displayed rests, setup and transitions. Gym queues and learning a movement can take longer; finish with the cooldown when your time is up.','Las estimaciones incluyen descansos mostrados, preparación y transiciones. Las esperas y aprender un movimiento pueden tomar más tiempo; termina con la vuelta a la calma cuando se agote tu tiempo.']
  ];
  window.ROUNDWORK_ADD_ES(pairs);
  window.ROUNDWORK_PLANNER_TEXT=pairs.map(([en])=>en);
  const E=window.ROUNDWORK_EVIDENCE;
  const L=(en,es)=>{window.ROUNDWORK_ADD_ES([[en,es]]);return en;};
  E.sources.push(
    {id:'progression-2009',type:'guideline',citation:'ACSM · 2009 · Med Sci Sports Exerc 41:687–708',doi:'10.1249/MSS.0b013e3181915670',originalTitle:'American College of Sports Medicine position stand. Progression models in resistance training for healthy adults',url:'https://pubmed.ncbi.nlm.nih.gov/19204579/',
      title:L('Experience, progression and rest intervals','Experiencia, progresión y descansos'),
      design:L('Historical ACSM position stand; published abstract consulted. General adult training, not a boxing trial.','Documento histórico de ACSM; resumen publicado consultado. Entrenamiento general de adultos, no un ensayo de boxeo.'),
      finding:L('Loading and progression depend on training experience and goals; demanding power and strength work needs recovery between sets.','La carga y la progresión dependen de la experiencia y los objetivos; el trabajo exigente de potencia y fuerza necesita recuperación entre series.'),
      application:L('Supports protecting rest in short sessions. Experienced power sets use 180-second rests; reduce work rather than rush recovery.','Apoya conservar el descanso en sesiones cortas. Las series de potencia para personas experimentadas usan descansos de 180 segundos; se reduce el trabajo en vez de apresurar la recuperación.'),
      limit:L('The newer 2026 ACSM statement informs general training. These menus and exact doses are app programming choices, not validated level thresholds.','El documento más reciente de ACSM de 2026 orienta el entrenamiento general. Estos menús y dosis exactas son decisiones de la app, no umbrales de nivel validados.')},
    {id:'time-efficient',type:'practice',citation:'NSCA · Personal Training Quarterly · consulted 8 October 2026',url:'https://www.nsca.com/education/articles/ptq/time-efficient-training/',
      title:L('Time-efficient resistance training','Entrenamiento de resistencia eficiente en tiempo'),
      design:L('Professional programming article; public guidance consulted.','Artículo profesional de programación; orientación pública consultada.'),
      finding:L('Exercise selection, volume and rest can be adjusted to goals and training experience.','La selección de ejercicios, el volumen y el descanso se ajustan a objetivos y experiencia.'),
      application:L('Short sessions prioritise major movement patterns, retaining warm-up and rest.','Las sesiones cortas priorizan patrones principales, conservando calentamiento y descanso.'),
      limit:L('Not a boxing intervention; it does not validate these time menus.','No es una intervención de boxeo; no valida estos menús de tiempo.')},
    {id:'talk-test',type:'practice',citation:'CDC · Physical Activity Basics · 2025',url:'https://www.cdc.gov/physical-activity-basics/measuring/index.html',
      title:L('Relative effort and the talk test','Esfuerzo relativo y prueba del habla'),
      design:L('Public-health guidance; relative intensity section consulted.','Orientación de salud pública; sección de intensidad relativa consultada.'),
      finding:L('The same exercise can feel different across fitness levels; speech and perceived effort help monitor intensity.','El mismo ejercicio puede sentirse distinto según la condición física; hablar y percibir el esfuerzo ayudan a controlar la intensidad.'),
      application:L('Extra time goes mainly to conversational aerobic work; slow down when comfortable speech becomes difficult.','El tiempo adicional se dedica principalmente a trabajo aeróbico que permite conversar; baja el ritmo si hablar cómodamente resulta difícil.'),
      limit:L('The app’s easy 3–5/10 target is conservative programming, not a heart-rate test or an individual medical assessment.','El objetivo suave de 3–5/10 de la app es una decisión conservadora, no una prueba de frecuencia cardiaca ni una evaluación médica individual.')}
  );
  E.groups.push({title:L('How level and time are adapted','Cómo se adaptan nivel y tiempo'),ids:['acsm','progression-2009','time-efficient','talk-test','boxing','sleep'],exercises:window.BOXING_DATA.exercises.map(ex=>ex.id)});
  E.reviewed='2026-10-08';
})();
