/* Public publisher-hosted demonstrations located 6 October 2026.
   Videos teach movement; research and programming remain in evidence.js/data.js.
   Never download/rehost clips, or infer an app dose from a video's workout. */
window.ROUNDWORK_VIDEOS = (() => {
  const pairs=[];
  const L=(en,es)=>{pairs.push([en,es]);return en;};
  const V=(id,provider,title,note)=>({id,provider,title,note,url:`https://www.youtube.com/watch?v=${id}`});
  const march=V('_Ox0N-Ab3Sc',"Doctor O’Donovan · Ella Boys, physiotherapist",L('Marching on the spot','Marcha en el sitio'),L('Use the marching demonstration only. ROUNDWORK sets your pace and duration; this is not a boxing conditioning workout.','Usa solo la demostración de marcha. ROUNDWORK establece el ritmo y la duración; este no es un entrenamiento de acondicionamiento para boxeo.'));
  const bike=V('NwwDBARCGgo','PureGym',L('Stationary bike setup','Ajuste de bicicleta estática'),L('Bike controls vary by model. Ask gym staff to check your seat fit. Follow the effort and interval times in your session.','Los controles varían según el modelo. Pide al personal que revise el ajuste del asiento. Sigue el esfuerzo y los intervalos de tu sesión.'));
  const shadow=V('6owVbMeExtA','FightCamp · Aaron Swenson',L('Shadowboxing basics','Fundamentos de boxeo de sombra'),L('Watch stance, guard and movement. Practise only punches and defences your coach has taught; follow your session rounds, not the video’s workout.','Observa la postura, la guardia y los desplazamientos. Practica solo golpes y defensas enseñados por tu entrenador; sigue las rondas de tu sesión, no el entrenamiento del video.'));
  const videos={
    warmup:{...march,title:L('Warm-up marching','Marcha de calentamiento'),note:L('This demonstrates the marching part of your warm-up. Then mobilise ankles, hips and shoulders, rehearse today’s exercises and do the light ramp-up sets in your written guide.','Muestra la parte de marcha del calentamiento. Después moviliza tobillos, caderas y hombros, ensaya los ejercicios del día y realiza las series ligeras de aproximación de tu guía escrita.')},
    jump:V('tZSYZdtbONc','NASM',L('Vertical jump and landing','Salto vertical y aterrizaje'),L('Use an unloaded jump and reset after every landing. Do not copy continuous jumps, deeper dips or extra repetitions.','Salta sin carga y vuelve a colocarte después de cada aterrizaje. No copies saltos continuos, descensos más profundos ni repeticiones adicionales.')),
    rotation:V('vSo6zTb1quM','OriGym',L('Side-on medicine-ball wall throw','Lanzamiento lateral de balón medicinal contra la pared'),L('The video catches the rebound. In this plan, let the ball settle and reset; use a light throwing ball and turn feet and hips with the torso.','En el video se atrapa el rebote. En este plan, deja que el balón se detenga y vuelve a colocarte; usa un balón ligero para lanzamientos y gira pies y caderas junto con el torso.')),
    chestThrow:V('upEOUUXso2Q','The Kenneth H. Cooper Institute',L('Medicine-ball wall chest pass','Pase de pecho con balón medicinal contra la pared'),L('Watch the two-hand release. The video uses rapid repeated catches; ROUNDWORK uses single throws with a full reset. Follow your guide’s safe distance and dose.','Observa el lanzamiento con las dos manos. El video usa recepciones rápidas repetidas; ROUNDWORK usa lanzamientos individuales con pausa para recolocarse. Sigue la distancia segura y la dosis de tu guía.')),
    squat:V('nfX7IFK9UNI','NASM',L('Goblet squat','Sentadilla goblet'),L('A kettlebell or dumbbell can show the goblet position. Use the equipment and controlled repetitions listed in your session.','La posición goblet puede mostrarse con pesa rusa o mancuerna. Usa el equipo y las repeticiones controladas indicadas en tu sesión.')),
    press:V('AduT4Eq-iP0','PureGym',L('Dumbbell bench press','Press de pecho con mancuernas en banco'),L('Use a flat stable bench, a manageable load and controlled repetitions. Follow ROUNDWORK’s sets and recovery.','Usa un banco plano estable, una carga manejable y repeticiones controladas. Sigue las series y los descansos de ROUNDWORK.')),
    row:V('ZRSGpBUVcNw','PureGym',L('Supported single-arm dumbbell row','Remo con mancuerna a una mano con apoyo'),L('Support one hand and knee on the bench; row without twisting. Complete the prescribed work on both sides.','Apoya una mano y una rodilla en el banco; rema sin girar el torso. Completa el trabajo indicado en ambos lados.')),
    pallof:V('HXrLaqNIkTs','PureGym',L('Cable Pallof press','Press Pallof en polea'),L('Stand side-on and resist rotation. Choose light resistance; complete both sides without adding twists.','Colócate de lado y resiste la rotación. Elige una resistencia ligera; completa ambos lados sin añadir giros.')),
    hinge:V('QFbZevA7dps','NASM',L('Dumbbell Romanian deadlift','Peso muerto rumano con mancuernas'),L('Keep a soft knee bend and move through the hips. Lower only as far as you can keep the trunk controlled.','Mantén una ligera flexión de rodillas y mueve las caderas. Baja solo hasta donde puedas controlar el tronco.')),
    lunge:V('aoT5WAJot-U','OriGym',L('Reverse lunge','Zancada hacia atrás'),L('Learn the backward step with bodyweight first; add light dumbbells only as your guide allows.','Aprende primero el paso hacia atrás sin carga; añade mancuernas ligeras solo según lo indicado en tu guía.')),
    pulldown:V('JGeRYIZdojU','PureGym',L('Lat pulldown to the chest','Jalón al pecho'),L('Pull in front of your head toward the upper chest. Use the machine’s thigh pad and avoid swinging.','Tira por delante de la cabeza hacia la parte superior del pecho. Usa el apoyo de muslos de la máquina y evita balancearte.')),
    sidePlank:V('ZpBJIRLGEgg','NASM',L('Side plank position','Posición de plancha lateral'),L('The video shows the straight-leg version. Use bent knees if needed, as your guide explains; stop before your hips drop.','El video muestra la versión con piernas estiradas. Usa rodillas flexionadas si lo necesitas, como explica la guía; detente antes de que caigan las caderas.')),
    sled:V('E6mhG8zzYEY','PureGym · trainer Tom',L('High-handle sled push','Empuje de trineo con agarre alto'),L('This is the straight-arm, high-handle version in your plan. Use controlled driving steps, not a sprint; keep your session’s distance and rest.','Esta es la versión de brazos extendidos y agarre alto de tu plan. Da pasos controlados de impulso, sin esprintar; respeta la distancia y el descanso de tu sesión.')),
    ropes:V('ZujykKeVZpM','PureGym · Josh Messara, personal trainer',L('Alternating battle-rope waves','Ondas alternas con cuerdas de batalla'),L('Watch alternating vertical waves with a fixed anchor. Keep the waves repeatable and follow the work/rest timer in ROUNDWORK.','Observa las ondas verticales alternas con anclaje fijo. Mantén ondas repetibles y sigue el temporizador de trabajo y descanso de ROUNDWORK.')),
    bike,
    walk:V('HxsFneJFM2c','PureGym',L('Treadmill walking setup','Preparación para caminar en cinta'),L('This demonstrates a powered treadmill. A clear outdoor route also works. Keep a conversational pace; no sprints in this easy slot.','Muestra una cinta encendida. También sirve una ruta exterior despejada. Mantén un ritmo que permita conversar; no hagas esprints en este bloque suave.')),
    shadow,
    cooldown:{...march,note:L('Use gentle marching only as an example of slowing down. Let breathing settle; do not add a new workout during your cooldown.','Usa la marcha suave solo como ejemplo de bajar el ritmo. Deja que se normalice la respiración; no añadas otro entrenamiento durante la vuelta a la calma.')},
    coach:{context:L('Your coach leads this session','Tu entrenador dirige esta sesión'),note:L('There is no video to copy for a coached session. Bring the equipment your coach requests and follow their feedback.','No hay un video que copiar para una sesión con entrenador. Lleva el equipo que te indique y sigue sus correcciones.')},
    rest:{context:L('Recovery is the plan today','Hoy el plan es recuperarte'),note:L('No exercise demonstration is needed for a rest day. Use the recovery steps below; extra hard training is not required.','No hace falta una demostración de ejercicio para un día de descanso. Sigue los pasos de recuperación de abajo; no necesitas entrenamiento intenso adicional.')},
    pushup:V('WDIpL0pjun0','NASM',L('Controlled floor push-up','Flexión de brazos controlada en el suelo'),L('The video shows a floor push-up. Raise your hands to a stable bench or wall if needed to leave three good repetitions in reserve.','El video muestra una flexión en el suelo. Apoya las manos en un banco estable o en la pared si necesitas dejar tres repeticiones buenas en reserva.')),
    fastPushup:V('0JUrOH--Kdk','NASM',L('Incline push-up setup','Preparación para flexión inclinada'),L('This demonstrates the incline position at a controlled pace. For this power slot, lower under control, push up quickly, keep hands planted and reset. No clap or hand release.','Muestra la posición inclinada a ritmo controlado. Para este bloque de potencia, baja con control, sube rápido, mantén las manos apoyadas y vuelve a colocarte. Sin palmadas ni despegar las manos.')),
    splitSquat:V('rlvpaDkc76g','PureGym',L('Split squat with both feet on the floor','Sentadilla dividida con ambos pies en el suelo'),L('Use bodyweight here. Keep both feet planted; do not elevate your rear foot or copy a heavier variation.','Hazlo sin carga aquí. Mantén ambos pies apoyados; no eleves el pie trasero ni copies una variante con más peso.')),
    bandRow:V('qykwviNOIyc','NASM',L('Standing anchored band row','Remo de pie con banda anclada'),L('Check your chest-height anchor before pulling. The band must be intact and attached to a suitable fixed point.','Revisa el anclaje a la altura del pecho antes de tirar. La banda debe estar en buen estado y sujeta a un punto fijo adecuado.')),
    bandPallof:V('LkYtiDAgUUM','E3 Rehab Exercise Library',L('Band Pallof press','Press Pallof con banda'),L('Use the stationary press portion only; do not add the walkout variation. Keep the chest-height band anchor to your side and resist rotation.','Usa solo la parte de press estacionario; no añadas la variante con desplazamientos. Mantén el anclaje de la banda a la altura del pecho a tu lado y resiste la rotación.')),
    deadbug:V('9RK9UUgKIQE','PureGym',L('Opposite-arm-and-leg dead bug','Dead bug con brazo y pierna opuestos'),L('Start with arms up and knees bent above the hips. Reach only as far as you can without arching your back.','Empieza con brazos arriba y rodillas flexionadas sobre las caderas. Extiende solo hasta donde puedas sin arquear la espalda.')),
    bridge:V('tqp5XQPpTxY','PureGym',L('Bodyweight glute bridge','Puente de glúteos sin carga'),L('Use the two-leg floor version without weights. Finish by aligning hips and thighs, not by arching the lower back.','Usa la versión en el suelo con ambas piernas y sin peso. Termina alineando caderas y muslos, sin arquear la zona lumbar.')),
    stepup:V('URHdW9js6DM','NASM',L('Step-up technique','Técnica de subida al escalón'),L('Choose a stable LOW step and bodyweight, even if the video shows a higher platform. Step down slowly and complete both legs.','Elige un escalón BAJO estable y trabaja sin carga, aunque el video muestre una plataforma más alta. Baja despacio y completa ambas piernas.')),
    bikeIntervals:bike,
    marchIntervals:march,
    easyMarch:march
  };
  [
    ['VIDEO DEMONSTRATION','DEMOSTRACIÓN EN VIDEO'],
    ['Watch demonstration','Ver demostración'],
    ['Open original video','Abrir video original'],
    ['Stop video','Detener video'],
    ['Quick mechanics · illustrations','Mecánica rápida · ilustraciones'],
    ['Video demonstration · more detail','Demostración en video · más detalle'],
    ['Illustrations show key positions and stay available offline. Use the video for a fuller view of the movement.','Las ilustraciones muestran las posiciones clave y están disponibles sin conexión. Usa el video para ver el movimiento con más detalle.'],
    ['KEY POSITIONS','POSICIONES CLAVE'],
    ['Videos need internet. Illustrations and written steps stay available offline after the app is saved.','Los videos necesitan internet. Las ilustraciones y los pasos escritos siguen disponibles sin conexión después de guardar la app.'],
    ['Tap the player’s play button. If it cannot load here, open the original video.','Pulsa el botón de reproducción del video. Si no carga aquí, abre el video original.'],
    ['Demonstrations show movement technique. Follow your session’s dose and ask a coach to check unfamiliar movements.','Las demostraciones muestran la técnica del movimiento. Sigue la dosis de tu sesión y pide a un entrenador que revise los movimientos que no conoces.'],
    ['ILLUSTRATIONS + VIDEOS','ILUSTRACIONES + VIDEOS'],
    ['Demonstration video directory','Directorio de videos de demostración'],
    ['Publisher-hosted videos were located on 6 October 2026. They demonstrate technique; they do not validate this workout or its effects on punch power. Video notes explain differences from the prescribed variation. Original audio and available captions are controlled by the publisher.','Los videos de sus editores se localizaron el 6 de octubre de 2026. Demuestran técnica; no validan este entrenamiento ni sus efectos sobre la potencia del golpe. Las notas explican diferencias respecto a la variante indicada. El audio original y los subtítulos disponibles dependen del editor.'],
    ['Video needs internet. Use the illustrations and written steps.','El video necesita internet. Usa las ilustraciones y los pasos escritos.'],
    ['Connect once to save the written steps and movement backups. Videos and external expert pages need internet. Offline availability depends on your browser retaining the app’s saved files.','Conéctate una vez para guardar los pasos escritos y las guías visuales. Los videos y las páginas externas necesitan internet. La disponibilidad sin conexión depende de que el navegador conserve los archivos de la app.'],
    ['The written steps and movement backups have been saved for offline use on this browser. Open the app once online on each phone. Videos and external expert pages need internet; browsers may clear saved files.','Los pasos escritos y las guías visuales se han guardado para usar sin conexión en este navegador. Abre la app una vez con internet en cada teléfono. Los videos y las páginas externas necesitan internet; los navegadores pueden borrar los archivos guardados.'],
    ['Offline saving is unavailable in this browser. The app works while online; videos and expert pages also need internet.','No se puede guardar sin conexión en este navegador. La app funciona con internet; los videos y las páginas externas también lo necesitan.'],
    ['Every gym movement opens with illustrated mechanics and written steps. Expand the video demonstration for a fuller view.','Cada movimiento del gimnasio se abre con la mecánica ilustrada y pasos escritos. Abre la demostración en video para verlo con más detalle.']
  ].forEach(pair=>pairs.push(pair));
  window.ROUNDWORK_ADD_ES?.(pairs);
  return Object.freeze(videos);
})();
