const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const base=path.join(__dirname,'..');let checks=0;
const ok=(x,msg)=>{assert(x,msg);checks++};
const el=()=>({addEventListener:()=>{},classList:{add:()=>{},remove:()=>{},toggle:()=>{}},setAttribute:()=>{},focus:()=>{},textContent:'',innerHTML:'',hidden:false});
const elements=new Map(), get=s=>{if(!elements.has(s))elements.set(s,el());return elements.get(s)};
const document={getElementById:s=>get('#'+s),querySelector:get,querySelectorAll:()=>[],body:{style:{},querySelectorAll:()=>[]},documentElement:{},createTreeWalker:()=>({nextNode:()=>null}),addEventListener:()=>{},dispatchEvent:()=>{}};
const context={window:{scrollTo:()=>{}},document,localStorage:{getItem:()=>null,setItem:()=>{}},NodeFilter:{SHOW_TEXT:4},MutationObserver:class{observe(){}},CustomEvent:class{},location:{hash:''},history:{replaceState:()=>{}},setInterval:()=>{},clearInterval:()=>{},setTimeout:()=>{},clearTimeout:()=>{},console,URL,Date,Map,Set,navigator:{onLine:true}};vm.createContext(context);
for(const file of ['data.js','es.js','es-ui.js','evidence.js','videos.js','choices.js','i18n.js','diagrams.js','choices-diagrams.js'])vm.runInContext(fs.readFileSync(path.join(base,file),'utf8'),context);
const {BOXING_DATA:D,ROUNDWORK_VIDEOS:V,RoundworkI18n:I}=context.window;
const unchanged=JSON.stringify(D);
for(const ex of D.exercises){const v=V[ex.id];ok(v,'Missing demonstration '+ex.id);ok(!!v.note,'Missing variant note '+ex.id);ok(I.translate(v.note,'es')!==v.note,'Spanish note '+ex.id);if(v.id){ok(/^[A-Za-z0-9_-]{11}$/.test(v.id),'Invalid video id '+ex.id);ok(v.url==='https://www.youtube.com/watch?v='+v.id,'Direct original link '+ex.id);ok(v.provider && v.title,'Missing attribution '+ex.id);ok(I.translate(v.title,'es')!==v.title,'Spanish title '+ex.id);}else ok(['coach','rest'].includes(ex.id)&&v.context,'Only non-exercise sessions omit video');}
ok(Object.values(V).filter(v=>v.id).length===D.exercises.length-2,'29 movement guides with videos');
ok(V.sled.id==='E6mhG8zzYEY'&&/high-handle/.test(V.sled.note),'High-handle sled variant');
ok(V.ropes.id==='ZujykKeVZpM'&&/alternating vertical waves/.test(V.ropes.note),'Ordinary anchored alternating waves');
ok(/keep hands planted/.test(V.fastPushup.note),'Incline power slot keeps hands planted');
ok(/single throws with a full reset/.test(V.chestThrow.note),'Repeated chest pass video must not override reset dose');
ok(/let the ball settle and reset/.test(V.rotation.note),'Rotational throw must not copy rebound catch');
ok(V.bikeIntervals.id===V.bike.id,'Bike intervals share setup, not prescriptions');
ok(V.marchIntervals.id===V.easyMarch.id,'Marching variants share technique, not intensity');
const original=fs.readFileSync(path.join(base,'app.js'),'utf8');
const app=original.replace(/  render\(\);\s*\}\)\(\);\s*$/,'  window.videoTest={guide,loadVideo,stopVideo,updateDemo,videoSection,closeModal};\n})();');
vm.runInContext(app,context);const T=context.window.videoTest;
for(const ex of D.exercises){T.guide(ex.id);const html=get('#modal-root').innerHTML;ok(html.includes('<section class="movement-preview"')&&html.includes('Quick mechanics · illustrations'),'Visible illustrations '+ex.id);ok(!html.includes('movement-backup'),'Illustrations never hidden in backup '+ex.id);ok(!html.includes('<iframe'),'No third-party load before click '+ex.id);ok(html.indexOf('id="demo-visual"')<html.indexOf('video-guide')||!V[ex.id].id,'Illustrations before optional video '+ex.id);if(V[ex.id].id)ok(html.includes('<details class="video-details" id="video-details">')&&!html.includes('id="video-details" open'),'Video initially collapsed '+ex.id);if(V[ex.id].id)ok(html.includes(V[ex.id].url)&&html.includes('data-video="load"'),'Specific video link and player '+ex.id);}
T.guide('sled');T.updateDemo(1);ok(get('#demo-step').textContent==='FRAME 2 / 3','Illustration frame navigation');T.updateDemo(0);T.loadVideo();let html=get('#video-stage').innerHTML;
ok(html.includes('youtube-nocookie.com/embed/'+V.sled.id),'Click loads correct clip');
ok(html.includes('autoplay=0')&&html.includes('playsinline=1'),'User plays manually on phone');
ok(html.includes('strict-origin-when-cross-origin'),'YouTube receives referrer identity');
ok(html.includes('allowfullscreen'),'Fullscreen control');
T.stopVideo();ok(get('#modal-root .video-guide').outerHTML.includes('data-video="load"')&&!get('#modal-root .video-guide').outerHTML.includes('<iframe'),'Stop removes player and restores optional video');ok(original.includes("if(!event.target.open)stopVideo()"),'Closing video stops hidden playback');
for(const text of ['Quick mechanics · illustrations','Video demonstration · more detail','ILLUSTRATIONS + VIDEOS'])ok(I.translate(text,'es')!==text,'Bilingual dual-guide labels '+text);
I.setLanguage('es');T.guide('ropes');T.loadVideo();ok(get('#video-stage').innerHTML.includes('hl=es&cc_lang_pref=es'),'Spanish player and caption preference');
context.navigator.onLine=false;T.guide('row');get('#video-stage').innerHTML='not-loaded';T.loadVideo();ok(get('#video-stage').innerHTML==='not-loaded','Offline tap does not attempt playback');
T.closeModal();ok(get('#modal-root').innerHTML==='','Closing removes the embedded player');
ok(JSON.stringify(D)===unchanged,'Visual update must not change training doses or routine');
const index=fs.readFileSync(path.join(base,'index.html'),'utf8'),sw=fs.readFileSync(path.join(base,'sw.js'),'utf8');
ok(index.indexOf('videos.js')<index.indexOf('i18n.js'),'Video translations load before translator');
ok(sw.includes('videos.js?v=1.4.2')&&sw.includes('roundwork-v1.4.2'),'Video catalog cached with current app');
ok(!sw.includes('youtube.com')&&!sw.includes('youtube-nocookie.com'),'External videos never falsely cached for offline');
ok(!original.includes('ILLUSTRATED GUIDES'),'Library advertises video guides');
console.log(`${checks} video checks passed: all ${D.exercises.length} guides, ${D.exercises.length-2} video mappings, variants, Spanish, offline handling, on-demand loading and unchanged training data.`);
